### ISSUE TITLE
question: why not use the "env" command?

### ISSUE THREAD

**Issue by taddei** [kentcdodds/cross-env#10]
This works for me on Mac, Linux and Windows:

```json
{
  "build": "env NODE_ENV=production webpack --config build/webpack.config.js"
}
```

**Comment by kentcdodds** [comment]
Do you have some documentation on that? I can't seem to find any information about it...

**Comment by kentcdodds** [comment]
Specifically for windows I mean.

**Comment by taddei** [comment]
now that you mention it, I don't remember. I think that git bash (windows) installs this command?

**Comment by kentcdodds** [comment]
Ah, and that's where this is valuable, you can't force windows to use git bash, even though it's good for them. Many of them just use regular command prompt. Thanks for bringing it up!
