### ISSUE TITLE
npm script with regex glob

### ISSUE THREAD

**Issue by adamgruber** [kentcdodds/cross-env#100]
This is my npm script:
```
"cross-env UV_THREADPOOL_SIZE=100 BABEL_DISABLE_CACHE=1 NODE_ENV=test nyc mocha --require test/helper.js \"test/spec/**/*.test.+(js|jsx)\""
```

After upgrading to 4.0.0, I get this error:
```
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `nyc mocha --require test/helper.js test/spec/**/*.test.+(js|jsx)'
```

Is this a bug with v4 or do I need to change how I am passing my args to `mocha`?

**Comment by kentcdodds** [comment]
This might be related to #99

**Comment by hgwood** [comment]
Definitely #99. @adamgruber could you try `\\\"test/spec/**/*.test.+(js|jsx)\\\"`?

**Comment by adamgruber** [comment]
I tried different combinations of escaping but none have worked so far. Here's a simplified script:
```
"cross-env mocha \\\"test/spec/**/*.test.+(js|jsx)\\\""
```
and the error:
```
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `cross-env mocha \"test/spec/**/*.test.+(js|jsx)\"'
```

I tried escaping the parenthesis:
```
"cross-env mocha \"test/spec/**/*.test.+\\(js|jsx\\)\""
```
but then I get this:
```
/bin/sh: jsx): command not found
```

**Comment by hgwood** [comment]
Applying the same analysis as [there](https://github.com/kentcdodds/cross-env/issues/99#issuecomment-292313519).

# original script

- The original text / what we can read in `package.json`: `"cross-env mocha --require test/helper.js \"test/spec/**/*.test.+(js|jsx)\""`
- The actual JSON value / what the shell sees:  `cross-env mocha --require test/helper.js "test/spec/**/*.test.+(js|jsx)"`
- The shell-parsed value / what cross-env gets as `process.argv`:

```
[ 'mocha',
  '--require',
  'test/helper.js',
  'test/spec/**/*.test.+(js|jsx)' ]
```

- Spawn call: `spawn('/bin/sh', ['-c', 'mocha --require test/helper.js test/spec/**/*.test.+(js|jsx)'])`
- What the spawned shell sees: `mocha --require test/helper.js test/spec/**/*.test.+(js|jsx)`

Regexp is not quoted so it is interpreted by the shell. That why it says `/bin/sh: -c: line 0: syntax error near unexpected token `('`.

# suggested fix

- The original text / what we can read in `package.json`: `"cross-env mocha --require test/helper.js \\\"test/spec/**/*.test.+(js|jsx)\\\""`
- The actual JSON value / what the shell sees:  `cross-env mocha --require test/helper.js \"test/spec/**/*.test.+(js|jsx)\"`
- The shell-parsed value / what cross-env gets as `process.argv`:

```
[ 'mocha',
  '--require',
  'test/helper.js',
  '"test/spec/**/*.test.+(js|jsx)"' ]
```

- Spawn call: `spawn('/bin/sh', ['-c', 'mocha --require "test/helper.js test/spec/**/*.test.+(js|jsx)"'])`
- What the spawned shell sees: `mocha --require "test/helper.js test/spec/**/*.test.+(js|jsx)"`

So it should work. I suspect `nyc` might be adding an additional processing layer here.

@adamgruber could try without `nyc`?

**Comment by hgwood** [comment]
I guess you could also try `test/spec/\\*\\*/\\*.test.+\\(js\\|jsx\\)`.

**Comment by adamgruber** [comment]
@hgwood My example [above](https://github.com/kentcdodds/cross-env/issues/100#issuecomment-291891577) was without nyc.

Taking your suggestion and escaping not just the parenthesis but also the pipe in my regex fixes it. So my working script is now:

```sh
"cross-env mocha --require test/helper.js \"test/spec/**/*.test.+\\(js\\|jsx\\)\""
```

Thanks for the help.
