### ISSUE TITLE
v4 regression in Windows

### ISSUE THREAD

**Issue by kellyselden** [kentcdodds/cross-env#103]
Here is v3 working in Linux and Windows https://github.com/kellyselden/fs-equal/pull/29/files
Here is v4 working in Linux and broken in Windows https://github.com/kellyselden/fs-equal/pull/28/files

Here are the logs https://ci.appveyor.com/project/kellyselden/fs-equal/build/1.0.79/job/t0rlvwmdg387ebvr#L480

specifically: `/**/*.js was unexpected at this time.`

It seems as the string escaping is a little off.

**Comment by kentcdodds** [comment]
This is probably related to #99
Care to weigh in with a suggested solution?

**Comment by kentcdodds** [comment]
This should be resolved.

**Comment by kellyselden** [comment]
Looks to be fixed. Thanks!
