### ISSUE TITLE
cross-env replaces `:` for variables that aren't PATH

### ISSUE THREAD

**Issue by paulcbetts** [kentcdodds/cross-env#106]
On Windows, if you try to use visionmedia/debug with cross-env, you will have a Bad Time, because now all of your `mynamespace:*` gets turned into `mynamespace;*` which doesn't work. cross-env should really only replace `:` => `;` for `PATH`, no other variable uses this convention

**Comment by kentcdodds** [comment]
This is a [documented breaking change](https://github.com/kentcdodds/cross-env/releases/tag/v4.0.0):

> If an env variable has : or ; in its value, it will be converted to : on UNIX systems or ; on Windows systems. To keep the old functionality, you will need to escape those characters with a backslash.

So you can simply do: `mynamespace\:*`

> cross-env should really only replace : => ; for PATH, no other variable uses this convention

I'm not very experienced with windows environment variable conventions, but if you can document that `PATH` is the only environment variable that uses this convention, then maybe we can do something here in another breaking change to restore the original behavior...

**Comment by paulcbetts** [comment]
I use Windows a lot :)  (also, I used to work on it at Microsoft) - I can definitely tell you that PATH is the only variable that has this convention. Furthermore, this actually is pretty bad because now you can't write an absolute path in Windows because `C:\Windows\Notepad.exe` now becomes `C;\Windows\Notepad.exe`

**Comment by kentcdodds** [comment]
Gotcha, yeah, that's annoying. Could you make a pull request that changes the behavior to apply to only the path variable?

**Comment by DanReyLop** [comment]
Note that the `NODE_PATH` variable also uses the same convention. I don't know if there are other languages with the same kind of `PATH` variables, but the `NODE_PATH` one seems relevant :)

**Comment by paulcbetts** [comment]
@kentcdodds Done and done

**Comment by kentcdodds** [comment]
Could you test out `cross-env@5.0.0-beta.0`? Let us know whether it works in https://github.com/kentcdodds/cross-env/pull/108

**Comment by rcollette** [comment]
This beta version fixes the issue for me.

**Comment by vzaidman** [comment]
+1 for the bug.
+1 that beta 0 works.

**Comment by kentcdodds** [comment]
Thanks! I think it's about time to merge and release!

**Comment by kentcdodds** [comment]
Released. Thanks everyone!
