### ISSUE TITLE
cross-env@4.0.0 hangs forever on Node 5

### ISSUE THREAD

**Issue by nkbt** [kentcdodds/cross-env#109]
No idea why on node 5... Node 4, 6 and 7 are all sweet, but running script on Node 5 hangs forever.

Some more details on https://travis-ci.org/nkbt/nightwatch-autorun/jobs/224296188

**Comment by kentcdodds** [comment]
Could you try `cross-env@5.0.0-beta.0`? Maybe that'll magically fix it?

**Comment by nkbt** [comment]
Sure, let me try that :)

It is just very interesting fact that only node5 is affected.
-- 
Nik Butenko
nik@butenko.me
http://github.com/nkbt

**Comment by kentcdodds** [comment]
Give this a shot and file a new issue if you have trouble.

**Comment by nkbt** [comment]
Thanks, all's good now!
