### ISSUE TITLE
Add conditional equality checking

### ISSUE THREAD

**Issue by MadLittleMods** [kentcdodds/cross-env#11]
Add conditional basic equality match checking to be able compose script hooks to only run when certain environment criteria are met.

```json
{
  "scripts": {
    "postinstall": "cross-env NODE_ENV==development && npm run build"
  }
}
```

 - `==`
 - `!=`

Perhaps this should be a separate module `argv-get-env` to match up with [`argv-set-env`](https://www.npmjs.com/package/argv-set-env).

**Comment by kentcdodds** [comment]
That's not a bash feature is it? You're just asking that we add this as a feature if cross-env?

**Comment by kentcdodds** [comment]
Yeah, this isn't really a bash feature, so it's out of scope for this project.

Personally, for the `postinstall`, I would just have it reference a script that did the check itself. Or you could write another module that does what you're trying to do.

Good luck!

**Comment by MadLittleMods** [comment]
The check could be in a separate script in the project and would be necessary for complex criteria.

@kentcdodds  The composabiltiy works, I based it off this example for unix environements: http://stackoverflow.com/questions/23076968/npm-postinstall-only-on-development

**Comment by kentcdodds** [comment]
You could compose this with something like [`if-env`](https://www.npmjs.com/package/if-env)

**Comment by MadLittleMods** [comment]
@kentcdodds This is exactly what I was looking for, thanks for pointing it out :grinning:
