### ISSUE TITLE
Does corss-env work with React-Native?

### ISSUE THREAD

**Issue by kimjuny** [kentcdodds/cross-env#110]
I'd tried to do this lots of ways, environment variables are just not able to pass to React-Native, am I doing it incorrectly or just cross-env won't work with React-Native?

**Comment by kentcdodds** [comment]
I don't use React-Native, but it should totally work. If you could reproduce this in a separate repo, then it may be easier for people to help you :)

**Comment by kimjuny** [comment]
According to balbel [document](https://babeljs.io/docs/usage/babelrc/#env-option), the env key will be taken from process.env.BABEL_ENV.

I tried to set BABEL_ENV a different value by `cross-env BABEL_ENV=dev_rn`, react-native app still use env.development configuration(not env.dev_rn) in my .babelrc, I just started a brand new react-native app(react-native init testproject)...

**Comment by kentcdodds** [comment]
Yeah, it could be any number of things honestly. This is why having a minimal, reproducible example is so helpful. I'm afraid I don't have much time to help, but try digging a little bit. I'm happy to review [a pull request](http://makeapullrequest.com/) that improves the experience :)

**Comment by hgwood** [comment]
@kimjuny does it work without cross-env? I mean does `BABEL_ENV=dev_rn react-native run-ios` (or the native Windows equivalent) work?

**Comment by kentcdodds** [comment]
Feel free to re-open once you've dug a little further. But I'm pretty sure this has little to nothing to do with cross-env.

**Comment by ortonomy** [comment]
We're having an issue where react-native complains about missing ``websockets`` module when using cross-env. I think that websockets is part of a dependency for cross-env, and that RN javascript core can't require it properly. Thoughts?

**Comment by KingAmo** [comment]
see https://stackoverflow.com/questions/33117227/setting-environment-variable-in-react-native
