### ISSUE TITLE
Set variable from command output

### ISSUE THREAD

**Issue by martinschayna** [kentcdodds/cross-env#111]
I'am trying to find a **cross platform** way for execute command, capture its output and put it as argument to another command. This is very common on a Linux OS via `` `command` `` or `$(command)`. 

I can use it in a npm run script:
```
"scripts": {
   "check": "jest --findRelatedTests `git diff --names-only HEAD`"
}
```
But this won't work on Windows OS. I think it would be a perfect task for `cross-env`, such as:
```
"scripts": {
   "check": "cross-env TEST=`git diff --names-only HEAD` jest --findRelatedTests $TEST"
}
```
Indeed, currently it'll not work. But could be possible?

**Comment by kentcdodds** [comment]
I agree this is a great pattern. This is not possible right now with cross-env. I think that it's out of scope for the project. There may actually be another project that would allow you to do this and they could compose together: `some-thing cross-env TEST=`git diff --names-only HEAD` jest --findRelatedTests $TEST`

Sorry, but I'm going to mark this one as out of scope. If you do find another solution, I'd welcome a note in the README about it!
