### ISSUE TITLE
Set multiple environment doesn't work in webpack 2.4.1 for production build

### ISSUE THREAD

**Issue by kopax** [kentcdodds/cross-env#113]
Hi, I have tried the following and I still can't set two environments when I do a production build : 

    cross-env NODE_ENV=production NODE_ACTIVE_PROFILES=preproduction node server

**versions**

- webpack v2.4.1
- cross-env v3.1.3 and v5.0.0

I am using webpack as module bundler, this is how I configured the env in webpack : 

```js
  plugins: options.plugins.concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
        NODE_PROFILES_ACTIVE: JSON.stringify(process.env.NODE_PROFILES_ACTIVE),
      },
    }),
    new webpack.NamedModulesPlugin(),
  ]),
```

I can successfully get `NODE_ACTIVE_PROFILES` if the server is not started with the `production` build of webpack.

This command works:

    cross-env NODE_ENV=development NODE_ACTIVE_PROFILES=preproduction node server

In production, I can only read `NODE_ENV`. Is this a cross-env issue or webpack related?

**Comment by kentcdodds** [comment]
Hi @kopax,
Thanks for bringing this up. Could you create an isolated small repository that reproduces this issue?

**Comment by hgwood** [comment]
I don't really understand what you are trying to do but I see sometimes you refer to `NODE_ACTIVE_PROFILES` and sometimes to `NODE_PROFILES_ACTIVE`. Could that be your issue?

 If not then could you provide us with a minimal repo/gist that reproduces the issue? I'll close in the meanwhile.

**Comment by kopax** [comment]
Hi @hgwood, it appear that I needed to build the production build using this variables, not only start the express server. 

Webpack create a build with only `html+css+js+fonts`. Logically this env needed to be exported that's why my cross-env was ignored.
