### ISSUE TITLE
Can you unset with cross-env?

### ISSUE THREAD

**Issue by rws-github** [kentcdodds/cross-env#114]
I can't seem to make sure that an environment variable is undefined or has an empty value.

**Comment by kentcdodds** [comment]
That's not a use case that we've ever intended to support. Is that something you can do with normal shell?

**Comment by danewilson** [comment]
v4 allowed us to effectively unset variables across environments like this: `FOO=''` (`FOO=` also worked on Linux/Mac OS but not on Windows).

v5 throws an ENOENT error when this same syntax is used (`FOO=` or `FOO=''` or `FOO=""`). It would be nice to have this scenario catered for in v5 as well.

**Comment by kentcdodds** [comment]
Gotcha. Could someone find out how this broke?

**Comment by danewilson** [comment]
I did what I should have done in the first place and checked the release notes for v5 and this breaking change caught my eye:

"Scripts using quotes or escape sequences will see a difference in behavior.
Switching to the second bin should resolve any issue."

Lo and behold, changing to `cross-env-shell` allows us to use the `FOO=''` behaviour as before. If this is all as expected then I'm happy for this to be closed.

**Comment by kentcdodds** [comment]
Yup, sounds right!

**Comment by turnerhayes** [comment]
I'm still having issues with this @5.0.0; it looks like it's because of this: `var envSetterRegex = /(\w+)=('(.+)'|"(.+)"|(.+))/;`

Instead of `.*` it expects at least one character. Still happens using `cross-env-shell`.

**Comment by kentcdodds** [comment]
Ah yes, that's a bug. Happy to accept a pull request to change that `+` to `*`
