### ISSUE TITLE
allow format for overriding only if env var not already set

### ISSUE THREAD

**Issue by mateodelnorte** [kentcdodds/cross-env#115]
makefiles have a means of specifying that an env var should be set only if it's not already set. could we have a similar ability added to cross-env?

the syntax could look like `cross-env MYVAL?=my_value node index.js`

**Comment by kentcdodds** [comment]
Thanks @mateodelnorte,
But I think that's outside of the scope of what I want `cross-env` to be. You could build that into another lib though! Best of luck!

**Comment by mateodelnorte** [comment]
lame
