### ISSUE TITLE
npm start validate errors out

### ISSUE THREAD

**Issue by turnerhayes** [kentcdodds/cross-env#116]
`npm start validate` errors out due to a linting error:

     src/index.test.js
     95:15  error  More than one argument was passed to expect()  jest/valid-expect

It's complaining about [this](https://github.com/kentcdodds/cross-env/blob/master/src/index.test.js#L95) line.

**Comment by kentcdodds** [comment]
Yeah, that second argument to expect should be removed. Would you like to do that?

**Comment by turnerhayes** [comment]
Sure, I'll include it in my upcoming PR. I'm having a little trouble, though; I followed the CONTRIBUTING.md and created a branch for my changes, but after I got through `git start commit`, I have a commit but not sure how to push it; running `git push`, even with the `--set-upstream origin` option

**Comment by kentcdodds** [comment]
Ah, is this your first time contributing to open source? If so, welcome! Happy to have you! You might benefit from watching [this](https://makeapullrequest.com) first! Let me know how I can help after you've watched that 😀

**Comment by turnerhayes** [comment]
I try pushing but it says I don't have access.

**Comment by kentcdodds** [comment]
In that video course, I show you how to create a fork which you can push to.

**Comment by turnerhayes** [comment]
Ah, I can certainly use a fork; I was following the CONTRIBUTING.md directions, which specify cloning your repo and creating a branch on it (or that's what it sounded like to me) so I assumed that was your preferred contribution model and that you had somehow configured the repo to accept others' branches. I'll create a PR from a fork.

**Comment by turnerhayes** [comment]
My bad, it does say "fork". I somehow skipped over that.
