### ISSUE TITLE
Set session variable

### ISSUE THREAD

**Issue by vitalets** [kentcdodds/cross-env#118]
Hi! Is it possible to set terminal session variable with cross-env?
Currently if I do in terminal `cross-env MY_VAR=123` it does not really set variable.

**Comment by kentcdodds** [comment]
Hi @vitalets! That's not a use case that `cross-env` is intended to support I'm afraid. `cross-env` spawns a new process (the command you run with it) with the environment variable setup and that only applies to the process `cross-env` spawns. We don't plan on extending this beyond that. Sorry.

**Comment by vitalets** [comment]
Ok, thanks for the reply!
