### ISSUE TITLE
Not working from command line. It only works for me when running from package.json

### ISSUE THREAD

**Issue by jcfrancisIII** [kentcdodds/cross-env#12]
This is really just a question not an issue. Is it meant to work just from package.json?

Complete scrub here and I am not sure what I miss out on when using regular command prompt vs git bash or something else. This tool is already super helpful. Thanks.

**Comment by kentcdodds** [comment]
@jcfrancisIII, thanks for the question. This package is mostly just to make it so people can create `package.json` scripts in a way that run consistently across multiple platforms. If you're entering a command manually in your own environment, then you can enter it in such a way that works for your specific platform. This is just about sharing scripts. Does that help answer your question?

In general, I'd recommend that when you're developing, you use git bash if you're on windows. Most packages should take a windows environment into account, but many don't and it's just easier for you if you use git bash.

Good luck!
