### ISSUE TITLE
how to set complex env variable?

### ISSUE THREAD

**Issue by dengyaolong** [kentcdodds/cross-env#120]
I use cross-env to set env variable equal a script result. In unix, I set my npm scripts
```
{
   "pack": cross-env sha=$(git rev-parse --short HEAD) build"
}
```
however, in windows, it doesn't work? How to set the env var = a script result?

**Comment by kentcdodds** [comment]
Hi! I'm afraid that's not something that cross-env is intended to support and it is out of the scope of the project. Sorry. Good luck!
