### ISSUE TITLE
cross-env child process not capturing SIGINT

### ISSUE THREAD

**Issue by rbonomo** [kentcdodds/cross-env#121]
Sending SIGINT (ctrl+c) to process running with cross-env does not get captured by process.

**index.js**
```
process.stdin.resume(); // so the program will not close instantly

// catches ctrl+c event
process.on('SIGINT', () => {
  console.log('Ctrl-C...');
  process.exit(2);
});
```

Try
`node index.js`
and send SIGINT with 'ctrl+c'

Now try NPM script
`"start": "cross-env NODE_ENV=development node index.js"`
and send SIGINT with 'ctrl+c'

**Comment by kentcdodds** [comment]
Thanks for reporting this! Hmmm... I'll have to look into it later (or someone else is welcome to). What's your proposed solution?

**Comment by rbonomo** [comment]
Surprisingly this is because [npm does not forward signals to child process](https://github.com/npm/npm/pull/10868#issuecomment-192457737) (except SIGTERM).

Closing
