### ISSUE TITLE
Working directory changed

### ISSUE THREAD

**Issue by pke** [kentcdodds/cross-env#122]
When using `cross-env` in my `package.json` tasks I can see that `process.cwd()` is always the folder where the `package.json` is contained in. Even if I am in a subfolder 2 levels deep from the `package.json` where `process.cwd()` should actually say I am in that folder it still shows the folder where `package.json` is located in. Is that a `npm` issue or `cross-env`?

**Comment by kentcdodds** [comment]
That's npm

**Comment by pke** [comment]
Hmm... didn't find anything in their docs describing this behaviour. This makes things more difficult, uhm :/

**Comment by kentcdodds** [comment]
Yeah, sorry. There's an issue for it on npm (recently closed by their bot).
