### ISSUE TITLE
cross-env-shell doesn't appear to be working

### ISSUE THREAD

**Issue by markelog** [kentcdodds/cross-env#123]
I have put this in the package.json (as described in the doc): 

```js
"scripts": {
    "greet": "cross-env-shell GREETING=Hi NAME=Joe \"echo $GREETING && echo $NAME\""
  }
```

Then upon execution (with node@6.11.0 and node@8.1.3):
```
$ npm run greet
```

I get nothing in the output

**Comment by kentcdodds** [comment]
Hi there! :wave:

Hmmm... That's odd... Could you dig a little further to see what's going wrong?

**Comment by kuakman** [comment]
There is also one more weird behavior.
The arguments passed to script, i.e: ```npm run parent -- myarg``` doesn't carry over, neither the script.js or the child script when you have something like this in the package.json:
```
...
"scripts": {
  "parent": "cross-env somevar=test node script.js && npm run child",
  "child": "node someotherscript.js"
}
...
```

This one works and the node script "script.js" receives the arguments via **process.argv**
```
...
"scripts": {
  "parent": "cross-env somevar=test node script.js"
}
...
```

Details on my system:
* Mac OSX Sierra 10.12.5
* Node: 6.11.0
* Cross-env: 5.0.1

**Comment by kentcdodds** [comment]
That behavior is noted in the README 😀 environment variables do not reach out across `&&`. See the README for a workaround.

**Comment by kuakman** [comment]
@kentcdodds Oh sorry if I wasn't clear enough. I'm not referring to the environment variables.
What I was referring to was the arguments you could pass to the npm run-script command (aka: npm run). Check [Here](https://docs.npmjs.com/cli/run-script) the npm documentation. Thanks!

**Comment by kentcdodds** [comment]
Ah, gotcha. I'm not sure exactly what to do about that, do you have a suggestion?

**Comment by kentcdodds** [comment]
More specifically, what would you expect to have happen with the first case? Which of those two scripts would get the argument?

The basic idea is that adding cross-env should not change how things would behave without it when running on a Linux environment... Is that happening?

**Comment by kuakman** [comment]
@kentcdodds Well, I'm not familiar with the code base of cross-env. I just ran into that issue while trying to setup a project. I guess I need to look at the code and see if I can come up with a PR or something.

**Comment by kuakman** [comment]
Oh sorry about that, I think this is not related to cross-env specifically, but npm instead.
I just tried the following using the same example above.

```
"parent": "node parent.js && npm run child",
"child": "node child.js"
```
and none of those scripts received the arguments.

**Comment by sudo-suhas** [comment]
On windows 10 and node `v8.2.1`, the greet npm script works as expected.

**Comment by uspriya2006** [comment]
{
  "scripts": {
    "greet": "cross-env-shell GREETING=Hi NAME=Joe \"echo $GREETING && echo $NAME\""
  }
}

This prints nothing to the console, on OS X.

**Comment by gunzip** [comment]
same here on ubuntu 18

**Comment by edewit** [comment]
it seems to only work on windows, why was this issue closed?

**Comment by jas0ncn** [comment]
the same on macOS 10.15.1 and cross-env 6.0.3
