### ISSUE TITLE
variable not set - returning undefined

### ISSUE THREAD

**Issue by DaveyD** [kentcdodds/cross-env#124]
Hi there
I am trying to get this to work but I am not being successful
I have tried several commands, the simplest of which is:
```
  "scripts": {
     "test": "cross-env NODE_ENV=test webpack-dev-server",
  },
```
And when I `console.log(process.env.NODE_ENV)`, I get `undefined`.

What I originally wanted to do was the following:
```
  "scripts": {
    "start": "cross-env NODE_ENV=DEV run-p webpack jsonServer",
    "webpack": "webpack-dev-server",
    "jsonServer": "json-server -p 8080 --watch app/data/db.json"
  },
```
But I thought that maybe it was a problem with run-p (which is part of `npm-run-all` package), so I tried the simpler version that I posted above, but no matter what I try, I get `undefined`.

What am I doing wrong?

Thanks,
David

**Comment by kentcdodds** [comment]
Sorry, I'm not sure what's up, that should work...

**Comment by DaveyD** [comment]
Thanks for the quick reply
Is there any way I can debug this?

**Comment by kentcdodds** [comment]
I would start by going into your node_modules directory and adding console.log statements throughout the cross-env code

**Comment by DaveyD** [comment]
Just did what you mentioned...
Everything seems to be perfect in your code. The variable is being added to envSetters (as I was able to see with a console log).
I'm not sure why it's not working.

Actually - I just tried logging any kind to environment variable, and all return undefined. TEMP, windir etc, the all returned undefined.
It must be I am not understanding this correctly.

I have a react app which is being run by webpack.
In webpack.config, I set the entry file to be `app/index.js`
Where are these environment vars supposed to be visible?
I tried in `index.js` as well as other react component files, and in all of them the `process.env` is empty

Am I not understanding something correctly?

Please let me know
Thanks,
David

**Comment by kentcdodds** [comment]
Oh, no, you wont find environment variables available in your client-side bundle. Only in node. If you want to expose environment variables in the client, then you can either use [this babel plugin](https://babeljs.io/docs/plugins/transform-inline-environment-variables/) or webpack's [define plugin](https://webpack.js.org/plugins/define-plugin/). You'll want to do that in addition to using `cross-env`.

I'll close this issue because I'm 99% sure that's the problem. Good luck!

**Comment by DaveyD** [comment]
Awesome! Works perfectly!
Thanks so much for clarifying the confusion I was having!

David
