### ISSUE TITLE
no child_process for node?

### ISSUE THREAD

**Issue by stevenvachon** [kentcdodds/cross-env#126]
Wouldn't it better to not use a child process when the target program is node? This is especially nice when we're running something like [pm2](https://npmjs.com/pm2) which already does this.

Is this a problem?:
```shell
env-pass VAR=value node index.js
```
```js
if (program === "node" || path.resolve(program) === process.execPath) {
  Object.keys(vars).forEach(name => process.env[name] = vars[name]);
  process.chdir(path.dirname(entryPoint));
  require(entryPoint);
}
```

**Comment by kentcdodds** [comment]
Hi @stevenvachon. Thanks for bringing this up. I can understand what you mean, but I'm extremely hesitant to make any changes like that to this package. This tool is "done" and I only plan to do general maintenance. Feel free to fork it if you need this functionality. I'm sorry. Good luck!
