### ISSUE TITLE
cross-env-shell doesn't like relative paths

### ISSUE THREAD

**Issue by derekgreer** [kentcdodds/cross-env#127]
I've got a script as follows:

```
 "deploy:api": "cross-env-shell ./scripts/install.bat Services.Api ApiService $ENVIRONMENT",
```

I run this as so:

```
$> ENVIRONMENT=integration yarn run deploy:api
```

This results in the following error:

```
'.' is not recognized as an internal or external command,
operable program or batch file.
events.js:160
      throw er; // Unhandled 'error' event
      ^
```

yarn will run the relative script without cross-env-shell, but of course then you don't get the environment variable substitution

**Comment by kentcdodds** [comment]
Try:

```
 "deploy:api": "cross-env-shell \"./scripts/install.bat Services.Api ApiService $ENVIRONMENT\"",
```

**Comment by derekgreer** [comment]
I tried that, but got the same results.

**Comment by kentcdodds** [comment]
Seems like a bug. Happy to accept [a PR](http://makeapullrequest.com/) to fix it.

**Comment by sudo-suhas** [comment]
Should this be taken care in `commandConvert`? `parseCommand` correctly identifies the command but `spawn` chokes on `./`.
