### ISSUE TITLE
Cross-Env in package.json

### ISSUE THREAD

**Issue by rsmolkin** [kentcdodds/cross-env#138]
Hi, is it possible to re-write this with just using start and somehow make it work cross-platform?

```json
"scripts": {
    "start": "node_modules/.bin/nodemon ./bin/www --legacy-watch --exec node_modules/.bin/babel-node",
    "start-win": "node_modules/.bin/nodemon ./bin/www --legacy-watch --exec node_modules\\.bin\\babel-node"
}
```

**Comment by hgwood** [comment]
cross-env is a package to help assigning environment variables in a cross-platform way. It does not look like this is what you are trying to achieve, so I'm closing the issue.

That said, I might still be able to help. Try this:

```json
"scripts": {
  "start": "nodemon ./bin/www --legacy-watch --exec \"npm run babel-node --\"",
  "babel-node": "babel-node"
}
```

You don't need to spell out `./node_modules/.bin` when inside a npm script.

**Comment by rsmolkin** [comment]
Thanks, that totally worked!
