### ISSUE TITLE
Document default variable values

### ISSUE THREAD

**Issue by jacobrask** [kentcdodds/cross-env#140]
This works in my mac bash shell:

package.json:
`"scripts": { "build": "cross-env NODE_ENV=${NODE_ENV:-production} webpack" }}"`
`$ NODE_ENV=development npm run build` 

Will this work on Windows or is it just because my shell can handle it?

Thanks

**Comment by hgwood** [comment]
This will not work on Windows. cross-env will look for the environment variable named `NODE_ENV:-production`.

**Comment by hgwood** [comment]
I have closed the issue because the question was answered. If you meant to propose for cross-env to support this, you may re-open it after you have edited its title and summary to reflect that.

**Comment by kentcdodds** [comment]
Thanks @hgwood.

@jacobrask, `cross-env` is "done" as in it does what it's intended to do and will only be updated to fix bugs. If you need something more than what `cross-env` can do, then feel free to make another CLI to suite your needs :)

I realize this is probably not welcome news to you @jacobrask, and I'm sorry about that. I've just decided that it'd be better for everyone if `cross-env` stick with what it's doing today rather than pile complicated features on it. Thank you for understanding.

Good luck!

**Comment by jacobrask** [comment]
That's fine, thank you both for the project and for your answer 👍

**Comment by therealklanni** [comment]
@kentcdodds (cc @jacobrask) 

I added this feature and published it to npm under @therealklanni/cross-env. It's such a small change, and honestly, IMHO it adheres to the purpose of this package (you already resolve `${VAR}` so it's trivial to support `:-default` values). So if you'd like me to create a PR to merge that in, I'm happy to do so. 

If you're not interested in merging it, that's fine as well. I needed the same functionality, so seeing this thread and your response to it prompted me to add it in myself. Thanks for the great util!

**Comment by asos-albinotonnina** [comment]
@therealklanni hi, thanks for your contribution. I have a similar requirement, so I was trying this with your version:
`cross-env-shell Greet=${Greet:=production} "echo $Greet"`

Works on unix/osx: 
```
$ cross-env-shell Greet=${Greet:=production} "echo $Greet"
production
```

Not on Windows:
```
$ cross-env-shell Greet=${Greet:=production} "echo $Greet"
{Greet:=production}
```

What do you think?

**Comment by therealklanni** [comment]
@asos-albinotonnina 	you should probably post this question in an issue on my repo (you can reference this one there, so they're linked).

**Comment by albinotonnina** [comment]
@therealklanni my bad, missed a filter in a search field :)

![image](https://user-images.githubusercontent.com/37283/47256079-c4073600-d471-11e8-96a2-a904e58bbc53.png)

**Comment by therealklanni** [comment]
My apologies, I have enabled Issues. Not sure why they were disabled, maybe it was that way by default.
