### ISSUE TITLE
spaces not escaped property

### ISSUE THREAD

**Issue by derekgreer** [kentcdodds/cross-env#143]
- `cross-env` version: 5.0.5
- `node` version:  v6.11.2
- `yarn` version: 0.27.5
- platform: Windows
- shell: bash

Relevant code or config

```javascript
{
  "name": "issue",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "test0": "printf \"[%s]\\n\" \"%npm_package_main% %npm_package_version%\"",
    "test1": "cross-run printf \"[%s]\\n\" \"%npm_package_main% %npm_package_version%\"",
    "test2": "cross-env-shell cross-run printf \"[%s]\\n\" \"${npm_package_main} ${npm_package_version}\"",
    "test3": "cross-env-shell cross-run printf \"[%s]\\n\" \"${npm_package_main}\\ ${npm_package_version}\"",
    "test4": "cross-run cross-run printf \"[%s]\\n\" \"%npm_package_main% %npm_package_version%\""
  },
  "devDependencies": {
    "cross-env": "^5.0.5",
    "cross-run": "^1.0.1"
  }
}
```

What you did:

```
$> yarn run test2
```

What was expected:

```
[index.js 1.0.0]
```

What happened:

```
[index.js]
[1.0.0]
```

Problem description:

I've got a script that has spaces in the arguments I can't seem to get quoted.  I've included several tests in the script which seems to pinpoint the issue being with cross-env-shell.  To perform a similar scenario, test4 passes the output of `cross-run` to itself again which still prints the expected output of `[index.js 1.0.0]`.  The issue seems to be that cross-env-shell isn't preserving the argument list correctly.

**Comment by kentcdodds** [comment]
Interesting! Thanks for filling the issue!

Do you think you could [make a pull request](http://makeapullrequest.com) to fix this?

**Comment by arthurcavallari** [comment]
@derekgreer You need to use triple backslash when wrapping your commands in quotes, as stated in the docs.

Notice I changed \" to \\\" before ${npm_package_main} and after ${npm_package_version}

```
    "test2": "cross-env-shell cross-run printf \"[%s]\\n\" \\\"${npm_package_main} ${npm_package_version}\\\"",
```

**Comment by kentcdodds** [comment]
Thanks @arthurcavallari! I'm going to go ahead and close this issue.
