### ISSUE TITLE
How to use this to set multiple env variables

### ISSUE THREAD

**Issue by pke** [kentcdodds/cross-env#15]
I don't get the test code. It uses an array to test multiple arguments. 
But when using `cross-env` from within `package.json` how do I specify multiple args?

tried

`cross-env NODE_ENV=production SERVER_ENV=staging`
`cross-env NODE_ENV=production,SERVER_ENV=staging`

but it dies not set any of the variables.

**Comment by ztrange** [comment]
Finally works for me with multiple variables: 

```json
"scripts": {
  "debug": "cross-env NODE_PATH=. DEBUG=app:* nodemon bootload.js"
}
```

Hope it helps. 
Offtopic: NODE_PATH is used as described [here](https://gist.github.com/branneman/8048520)

**Comment by kentcdodds** [comment]
Yes, this should definitely work with multiple variables and I do this on many projects (just like @ztrange has).

@pke, could you create a repo that reproduces the issue you're seeing?

**Comment by pke** [comment]
well uhm it doesnt seem to work.

```
"codepush:android:staging": "cross-env MY_ENV=production CODEPUSH_ENV=staging && npm run build:bundle && code-push release-cordova app-android android -d staging",
"build:bundle": "cross-env NODE_ENV=production webpack -p --progress --colors",
```

will only set `NODE_ENV` to `production`. The other `MY_ENV` and `CODEPUSH_ENV` are not set

**Comment by kentcdodds** [comment]
Oh is that goes you're using it? That's a known issue: https://github.com/kentcdodds/cross-env/blob/master/README.md#known-limitations

**Comment by pke** [comment]
hmmm Thought it just sets a bunch of env vars and then spawns a new process that inherits those vars and so on. Guess  have to use `.sh` scripts then.

**Comment by kentcdodds** [comment]
Yeah, it's really an order of operations thing. With bash, `&&` totally isolates one script from another, so `cross-env` can't spawn the rest of your command because it's isolated from it.

**Comment by iugo** [comment]
If use webpack, multiple env variables maybe invalid. Should use webpack with `DefinePlugin`: 
https://stackoverflow.com/questions/48748054/how-to-set-multiple-env-variables-using-cross-env

**Comment by NoChapter** [comment]
try this 
```
cross-env NODE_ENV=production cross-env SERVER_ENV=staging
```

**Comment by Statfine** [comment]
````
new webpack.DefinePlugin({
  'process.env': {
    NODE_ENV: JSON.stringify(process.env.NODE_ENV),
    SERVER_ENV: JSON.stringify(process.env.SERVER_ENV),
  }
})

**Comment by hayden-apww** [comment]
anyone using laravel

webpack.mix.js (add this to the top to test)
```var webpack = require('webpack')

new webpack.DefinePlugin({
    'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
        SERVER_ENV: JSON.stringify(process.env.SERVER_ENV),
    }
})

console.log(process.env.NODE_ENV,process.env.SERVER_ENV)```

2 Variables need to be set (NODE_ENV and SERVER_ENV), this looks like this in your package.json

```  "scripts": {
    ...
    "development": "cross-env NODE_ENV=development SERVER_ENV=1 node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    ...
```
