### ISSUE TITLE
Proposal: `xenv` and `xenvsh` shorthands

### ISSUE THREAD

**Issue by jeffijoe** [kentcdodds/cross-env#151]
What do you think of adding `xenv` as a shorthand to `cross-env` and `xenvsh` as a shorthand to `cross-env-shell`? This would trim some characters off already crowded `scripts` lines in our `package.json`s. 😄

**Comment by kentcdodds** [comment]
Hey @jeffijoe! I actually prefer to be explicit and verbose when I can. I'd rather have long scripts that are clear and easy to understand than terse scripts that aren't (I realize that's subjective, but that's my opinion). If you'd like, you could publish your own small package that has those aliases and forwards all invocations to `cross-env`. In any case, I don't want to do this.

Thanks anyway!

**Comment by jeffijoe** [comment]
Fair enough. 😄
