### ISSUE TITLE
cross-env cannot work under partial window10

### ISSUE THREAD

**Issue by jayrom123** [kentcdodds/cross-env#152]
- `cross-env` version:^5.1.1
- `node` version: v8.2.1
- `npm` (or `yarn`) version: 5.3.0

Relevant code or config

```javascript

//packge.json
  "name": "",
  "scripts": {
    "test":"cross-env NODE_ENV=development&&node ./index.js"
  },
  "version": "",
  "devDependencies": {
    "cross-env": "^5.1.1"
  }
}


//index.js

var env = process.env.NODE_ENV;
console.log(env);

```

What you did: ```npm run test```

What happened:``` undefined ```

Reproduction repository:

**Comment by kentcdodds** [comment]
Hi @jayrom123,

This is because the two commands are executed entirely in isolation of one another. You can solve the problem by using [`cross-env-shell`](https://github.com/kentcdodds/cross-env#cross-env-vs-cross-env-shell) or by excluding the `&&` in your script:

```javascript

//packge.json
  "name": "",
  "scripts": {
    "test":"cross-env NODE_ENV=development node ./index.js"
  },
  "version": "",
  "devDependencies": {
    "cross-env": "^5.1.1"
  }
}


//index.js

var env = process.env.NODE_ENV;
console.log(env);

```
