### ISSUE TITLE
Can I set an environment variable from an argument passed to my script?

### ISSUE THREAD

**Issue by waynebloss** [kentcdodds/cross-env#154]
I want to use an argument passed to my npm script as part of the path that is given to a command. Like this:

`yarn my-script en-GB`

Where `en-GB` is a locale-id that I want to use as part of the path in my script, e.g. `"./intl/translation/en-GB"`. In the example script below, `ARG[0]` would resolve to `en-GB`.

```json
"my-script": "cross-env THEVAR=ARG[0] other-command \"./intl/translation/$THEVAR\""
```

If I can't do this with cross-env is there another package (or tactic) that comes to mind? Or, if you think there is any value to this perhaps you can make this a feature request or accept a pull request for it..although I'm not sure if my proposed syntax is any good.

**Comment by toddb** [comment]
It looks like `cross-env` doesn't like being changed while it is running. Funny that. So, let's not update `cross-env` as well:

```
    if (file.indexOf('cross-env') >= 0) {
      return;
    }
```

**Comment by surfjedi** [comment]
+1

**Comment by kentcdodds** [comment]
Thanks for the issue but this is definitely outside of the scope of cross-env. I'm not sure of any other package that does this, but it shouldn't be terribly complex to write a little script that does this yourself.

Good luck!
