### ISSUE TITLE
Load list of env vars from config file

### ISSUE THREAD

**Issue by janis91** [kentcdodds/cross-env#156]
My current problem is, that I want to set multiple environment variables. Everything works fine, but it could be improved by adding the possbility to load all environment variables from a .rc file or something similar. The script in npm otherwise gets very long when dealing with many env variables.

Therefore I want to propose a feature that allows to specify a configuration file like a run command file ('.cross-envrc') that can be used to specifiy all env variables that one wants to use with a npm script.

**Comment by kentcdodds** [comment]
Hi @janis91!

There are a lot of other tools that handle this use case (one even [mentioned in the README](https://github.com/kentcdodds/cross-env#other-solutions)). There's also a pretty popular project called [dotenv](https://github.com/motdotla/dotenv) that might help.

This use case is outside the scope of cross-env, so I'm going to close this issue. Thanks! Good luck :)

**Comment by janis91** [comment]
Hi @kentcdodds.
Sorry, didn't know that it isn't in the scope of cross-env. Thought of it like it could be a nice feature, but I didn't know that there is a project like env-cmd, either. Thanks for the hint!
dotenv is not was I was looking for, because I just want to reduce the length of my npm scripts ;-)

**Comment by KeesCBakker** [comment]
@janis91, did you find a solution for this problem?
