### ISSUE TITLE
Support setting env variables for all scripts at one time?

### ISSUE THREAD

**Issue by scottmas** [kentcdodds/cross-env#16]
So a common use case is that developers want to to always set a certain env variables for all scripts. For instance, the handy `NODE_PATH` variable that let's developers get rid of relative requires in their scripts. 

Currently, if we want to set this, we have to do it in each of the individual npm scripts like so: 
```
"scripts": {
   "test": "cross-env NODE_PATH=./es6 mocha"
   "something": "cross-env NODE_PATH=./es6 node blah.js"
   ...
}
```

But it would be super handy if we could just do in one place like so:

```
"cross-env": {
   "NODE_PATH": "./es6"
},
"scripts": {
   "test": "mocha"
   "something": "node blah.js"
   ...
}
```

I've looked into npm and I actually don't see any great way to support this, but there might be. It would be awesome IMO in any case though. What are your thoughts Kent? Both on feasibility and desirability?

**Comment by kentcdodds** [comment]
Hey there @scottmas! Long time no see :D

Thanks for the suggestion, but I'm not going to add this to the library. It's against the philosophy of this package of being small and simple. Adding this would add some magic ✨ that I'm not interested in adding.

I realize that it would be much nicer to just add this, but I'm going to go for simplicity and explicitness in the module. Thanks!

**Comment by scottmas** [comment]
Oh, that's cool. I thought that might be the case. I actually just came across your p-s module and I think I might bring the discussion there - I'm digging the clever `npm start ...` solution
