### ISSUE TITLE
cross-env eats backslashes

### ISSUE THREAD

**Issue by greggman** [kentcdodds/cross-env#167]
- `cross-env` version: 5.1.3
- `node` version: 8.9.4
- `npm` (or `yarn`) version: 5.6.0

Relevant code or config, in package.json

```
{
  "name": "test-cross-env",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test1": "cross-env TEST=foo node main.js",
    "test2": "node main.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cross-env": "^5.1.3"
  }
}
```

main.js

```
console.log(process.argv.join(' '));
```

What you did:

passed `\\someshare\somefolder` through cross-env

What happened:

cross-env ate a backslash

```
C:\Users\gregg\temp>npm run test1 -- \\someshare\somefolder

> test-cross-env@1.0.0 test1 C:\Users\gregg\temp
> cross-env TEST=foo node main.js "\\someshare\somefolder"

C:\Program Files\nodejs\node.exe C:\Users\gregg\temp\main.js \someshare\somefolder

C:\Users\gregg\temp>npm run test2 -- \\someshare\somefolder

> test-cross-env@1.0.0 test2 C:\Users\gregg\temp
> node main.js "\\someshare\somefolder"

C:\Program Files\nodejs\node.exe C:\Users\gregg\temp\main.js \\someshare\somefolder
```

Reproduction repository:

see above

Problem description:

cross-env eats backslashes. Not going through cross-env the backslashes make it into the program being excecuted

You can't even escape them with more backslashes

```
C:\Users\gregg\temp>npm run test1 -- \\\\someshare\somefolder

> test-cross-env@1.0.0 test1 C:\Users\gregg\temp
> cross-env TEST=foo node main.js "\\\\someshare\somefolder"

C:\Program Files\nodejs\node.exe C:\Users\gregg\temp\main.js \someshare\somefolder
```

**Comment by rob3c** [comment]
Normally, you pass args to npm scripts via `--`, as shown in the npm docs here:

https://docs.npmjs.com/cli/run-script

Otherwise, you're just passing the args to `npm`, not your script. If they make it through somehow, then you probably got lucky.

Have you tried the documented way like this?:
```
> npm run test1 -- \\someshare\somefolder
```

**Comment by greggman** [comment]
Sorry, there was a typo in my original message. Why don't you actually try it and you'll see the bug

**Comment by kentcdodds** [comment]
Yes, looks like it's probably a legit bug. Feel free to [make a pull request](http://makeapullrequest.com) to fix this :)

**Comment by rob3c** [comment]
@greggman LOL at the thumbs down for trying to give you legitimate advice for the code you *actually* posted. Your 'typo' makes a huge difference in the behavior, but I guess we're supposed to read your mind instead of your text.

**Comment by greggman** [comment]
sorry I tried to helpful. won't bother next time

**Comment by kentcdodds** [comment]
@rob3c, that tone was unappreciated. Thank you both for trying to be helpful in general.
