### ISSUE TITLE
support path variables with multiple values 

### ISSUE THREAD

**Issue by Illniyar** [kentcdodds/cross-env#17]
NODE_PATH variable (as well as other environment variables) support multiple values (I.E. setting NODE_PATH=/home/usr:/home/lib ) .

However in windows the delimiter is a semicolon (;) and in other oses it's a colon (:) .

To support this cross-env needs to replace colons with semicolons in windows in the proper variables.

Currently I suggest adding a flag (-m) that denotes that the next environment variable should be processed (to prevent breaking backward compatibility).

**Comment by kentcdodds** [comment]
See #19.

I neglected to say thank you for the PR. I appreciate that you put time into it and I'm sorry that it wont make it into the project.

**Comment by Illniyar** [comment]
I hate opening bugs without adding a PR if I can :) , sometimes that doesn't work out.
No worries.

Frankly I don't want to use NODE_PATH, but I don't like any of the other ways of having an absolute path in require in server-side code. 
If you have a better solution, I'd love to know it :)

**Comment by kentcdodds** [comment]
`<hug>`

> I hate opening bugs without adding a PR if I can :)

`</hug>`

Sure! I'm a big fan of using babel plugins to solve my problems, and there's a great one called [babel-plugin-module-alias](https://github.com/tleunen/babel-plugin-module-alias) that I use for this. I recommend against using it too much, but for a handful of utilities and that kind of thing it's really handy.
