### ISSUE TITLE
cross-env is swallowing "Ctrl + C" command on Windows 10

### ISSUE THREAD

**Issue by bennyn** [kentcdodds/cross-env#178]
- `cross-env` version: 5.1.5
- `node` version: 8.9.4
- `yarn` version: 1.3.2

Relevant code or config:

**package.json**

```json
"start": "cross-env NODE_ENV=production node dist/app/monitor.js",
```

**monitor.ts**

```javascript
import {Monitor} from 'forever-monitor';
import * as path from 'path';

let child: Monitor | undefined = undefined;

function exit(signal: string) {
  console.warn(`HERE I AM!!`);
  if (child) child.stop();
  process.exit(0);
}

process.on('SIGINT', exit);

child = new Monitor(path.join(__dirname, 'index.js'));

child.start();
```

What you did:

1. I started my transpiled "monitor.js" file using `node dist/app/monitor.js`
2. I hit `Ctrl + C` (on Windows 10) while the program was running
3. I saw the "HERE I AM!!" log message, because my code received a `SIGINT`
4. I tried the same again but this time with `cross-env` using `npx cross-env NODE_ENV=production node dist/app/monitor.js`
5. I hit `Ctrl + C`
6. I couldn't see the "HERE I AM!!" log message because it looks like cross-env is eating up my `Ctrl + C` input

Expected result:

I was thinking that my code will run into the `exit` function when running my program with `cross-env` using `npx cross-env NODE_ENV=production node dist/app/monitor.js` and pressing `Ctrl + C` but unfortunately it doesn't. 

My `process.on('SIGINT')` handler is only called when running ` node dist/app/monitor.js` (without "cross-env").

**Comment by kentcdodds** [comment]
Thanks for the report @bennyn. Would you be willing to dig a little deeper and suggest a solution for this problem?

**Comment by bennyn** [comment]
I will try to dig a little deeper but first I need to understand how signal interrupts are passed on in Node.js. 

I saw that @slavik57 reported something similar ([CTRL+C does not kill the child process](https://github.com/kentcdodds/cross-env/issues/139)) and traced it down to Node itself. 🤔

**Comment by bennyn** [comment]
**Great insights!** I found out that if I replace `cross-env` with `cross-env-shell`, then my program receives the `'SIGINT'` on Windows.

I then followed your [best practices](https://www.npmjs.com/package/cross-env#usage) and split my `start` script into environment variable assignment and execution:

```json
"start": "yarn start:monitor:env",
"start:monitor":" "cross-env-shell node dist/app/monitor.js",
"start:monitor:env": "cross-env NODE_ENV=production yarn start:monitor"
```

This works now for me so I will close the isse! 🎉 But it might be considered mentioning this within the `README.md` file. What do you think?
