### ISSUE TITLE
Regression in npm variable substitution on Windows with 5.2.0

### ISSUE THREAD

**Issue by mdurling** [kentcdodds/cross-env#185]
- `cross-env` version: 5.2.0
- `node` version: 8.9.4
- `yarn` version: 1.3.2

Relevant code or config

![cross-env](https://user-images.githubusercontent.com/3439869/41729235-b7c3d31a-7546-11e8-964e-ec4dfdc58e69.PNG)

What you did: Using `cross-env` to generate parameters from npm environment variables.

Problem description: Variable substitution not happening in version 5.2.0

![5 2](https://user-images.githubusercontent.com/3439869/41729326-f53dece4-7546-11e8-8771-b4835d82a498.PNG)

Suggested solution: Restore behavior present in 5.1.6

![5 1 6](https://user-images.githubusercontent.com/3439869/41729332-f881af4e-7546-11e8-9c62-2d4ce7489f85.PNG)

**Comment by singhsoldier13** [comment]
+1

**Comment by kentcdodds** [comment]
I'm afraid that I don't have time to dedicate to this package and nobody has made any pull requests to fix this so no there are no releases planned.
