### ISSUE TITLE
Not working for me on Azure

### ISSUE THREAD

**Issue by lordbah** [kentcdodds/cross-env#188]
- `cross-env` version:
5.2.0
- `node` version:
8.5.0
- `npm` (or `yarn`) version:
6.1.0

Relevant code or config

```javascript

```

What you did:
Deploy a project to Azure which uses cross-env in package.json

What happened:
npm install runs, then
> npm run clean && cross-env NODE_ENV="production" webpack
> marvin@0.2.0 clean D:\home\site\repository
> rm -rf ./build
'cross-env' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! marvin@0.2.0 client:build: `npm run clean && cross-env NODE_ENV="production" webpack`
npm ERR! Exit status 1

Reproduction repository:

Problem description:
cross-env was not recognized as a command.

I noticed that on my local system I have node_modules\.bin which contains cross-env.cmd, while on Azure I don't see a .bin folder under node_modules.

Suggested solution:

**Comment by kentcdodds** [comment]
Sorry for not responding to this earlier. It's been long enough that I'm going to close this issue. If you're still experiencing problems, please open a new issue.
