### ISSUE TITLE
npm install does not work inside VS code in a meteor project, but does at the system powershell level. Windows 10.

### ISSUE THREAD

**Issue by Rafael-Menis** [kentcdodds/cross-env#190]
- `cross-env` version: 5.2.0
- `node` version: 8.11.4
- `npm` (or `yarn`) version: 5.6.0

Relevant code or config
Type in "npm install --save-dev cross-env" inside of a meteor project directory.

What you did: Type in "npm install --save-dev cross-env" inside of a meteor project directory.

What happened:

```
npm ERR! path C:\Users\USERNAME\source\repos\simple-todos\node_modules\meteor-node-stubs\node_modules\base64-js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\USERNAME\source\repos\simple-todos\node_modules\meteor-node-stubs\node_modules\base64-js' -> 'C:\Users\USERNAME\source\repos\simple-todos\node_modules\meteor-node-stubs\node_modules\.base64-js.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USERNAME\AppData\Roaming\npm-cache\_logs\2018-09-10T05_10_20_692Z-debug.log
Reproduction repository:
```

Problem description: When I try to install cross-env in visual studio code inside of a meteor project directory, it throws those errors. If I go into regular powershell and type "npm install cross-env" it works fine.

Suggested solution: This might be a problem on meteor's end or a problem with how npm ignores files like here (https://stackoverflow.com/a/18020195). I'm not sure how to fix this, but figured it was worth raising as an issue.

**Comment by Noitidart** [comment]
Did you ever figure this out? I'm not using meteor. I'm doing electron, and I can't get cross-env nor cross-env-shell to set NODE_ENV. I used system level, and vscode level terminals.

**Comment by kentcdodds** [comment]
Sorry for not responding to this earlier. It's been long enough that I'm going to close this issue. If you're still experiencing problems, please open a new issue. However, I don't believe this is an issue we can resolve within cross-env.
