### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by paulcanning** [kentcdodds/cross-env#191]
Node - v10.7.0
NPM - 6.1.0
Cross-env - 5.2.0

Script - `"test": "cross-env NODE_ENV=production echo %NODE_ENV%"`

Echoes `%NODE_ENV%` not `production`

**Comment by kentcdodds** [comment]
You're correct. The script is evaluated that way before it's passed to cross-env. Try cross-env-shell if you need to do that.

**Comment by paulcanning** [comment]
Please see edit, I need to try and run cross-env via command line (following this tutorial https://nextjs.org/learn/basics/deploying-a-nextjs-app/run-two-instances) but the command isn't recognised.

**Comment by kentcdodds** [comment]
Make sure they're dependencies and not just devDependencies

**Comment by Noitidart** [comment]
> 
> 
> Make sure they're dependencies and not just devDependencies

I tried this, but still not working :( On Windows 10 :(

**Comment by Noitidart** [comment]
Here is picture of my scripts:

![image](https://user-images.githubusercontent.com/6372489/58230509-67127d80-7ce9-11e9-8fef-833471451bd3.png)
