### ISSUE TITLE
--inspect

### ISSUE THREAD

**Issue by xxyyzz2050** [kentcdodds/cross-env#196]
how to run a script using --inspect option to debug with chrome devtools?

packages.json : 
  "scripts": {
    "dev": "cross-env NODE_ENV=development nodemon server/index.js --watch server --inspect",
    "build": "nuxt build",
    "start": "cross-env NODE_ENV=production node server/index.js --inspect",
    "generate": "nuxt generate",
    "lint": "eslint --fix --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },

**Comment by vzaidman** [comment]
maybe
"dev": "cross-env NODE_ENV=development \"nodemon server/index.js --watch server --inspect\"",
?

**Comment by xxyyzz2050** [comment]
it is already in my question and it dosen't work

@vzaidman

**Comment by glittle** [comment]
The "--inspect" option doesn't seem to exist.

I've found that running it as is gives messages in the console like:

> Uncaught TypeError: Object(...) is not a function at eval (main.js?3479:18)

And the link provided by Chrome takes me to the 18th line of my `main.js` file.

**Comment by kentcdodds** [comment]
Sorry for not responding to this earlier. It's been long enough that I'm going to close this issue. If you're still experiencing problems, please open a new issue. From the look of it, this seems unrelated to cross-env.
