### ISSUE TITLE
cannot find module '..'

### ISSUE THREAD

**Issue by lixiaozhangme** [kentcdodds/cross-env#197]
![image](https://user-images.githubusercontent.com/19645470/51238539-16dd8480-19b2-11e9-91dd-cce625c069f7.png)
![image](https://user-images.githubusercontent.com/19645470/51239230-c5ce9000-19b3-11e9-8a31-d47f6eedd0fe.png)

It was still possible before, suddenly it will not work.

**Comment by zhuangya** [comment]
IMHO, this is not a proper way to use any npm modules.

or, maybe try `console.log(require('fs').readdirSync('..'))` to check the result?

**Comment by kentcdodds** [comment]
Sorry for not responding to this earlier. It's been long enough that I'm going to close this issue. If you're still experiencing problems, please open a new issue.

**Comment by kentcdodds** [comment]
Also, @zhuangya is correct. This module is not intended to be used like that.
