### ISSUE TITLE
spawn ENOENT error [and possible fix?]

### ISSUE THREAD

**Issue by NogsMPLS** [kentcdodds/cross-env#2]
Running windows 7, node 4.2.2 x64 bit, npm 2.14.7.

I get the following error when using cross-env:

![cross-env-error](https://cloud.githubusercontent.com/assets/6899011/11096075/e2773bc0-885d-11e5-9e29-dd23f544aeb9.PNG)

After a bunch of digging around, I found that if I replace the usage of ```spawn``` in cross-env with cross-spawn (https://www.npmjs.com/package/cross-spawn) the issue goes away for me.

I can put in a PR if you think adding this dependency is alright.

**Comment by kentcdodds** [comment]
Yes! Please do! I ended up creating [`argv-set-env`](https://www.npmjs.com/package/argv-set-env) because of this problem and I haven't come back to find out what the root issue was. I look forward to your PR :+1:
