### ISSUE TITLE
why create two process?

### ISSUE THREAD

**Issue by mh0625** [kentcdodds/cross-env#202]
- `cross-env` version: 5.2.0
- `node` version: 10.4.1
- `npm` (or `yarn`) version: 6.1.0

Relevant code or config
package.json scripts:
```javascript
"build-test": "cross-env ENV=test nuxt build",
```

What you did:

```
"build": "nuxt build",  // only one process

"build-test": "cross-env ENV=test nuxt build",  // have two process
```

What happened:

![image](https://user-images.githubusercontent.com/10876559/55959137-c322c480-5c9c-11e9-8dbd-90a55d942074.png)

Problem description:

I want to use cross-env modify environment, when I execute `npm run build-test` command, it will create two process, why?

**Comment by RafaRochaS91** [comment]
Because your actually calling the `nuxt build` again. It's a matter of package.json script scoping. just use `"build-test": "cross-env ENV=test build"`. Since `build` is already defined above.

**Comment by caiquecastro** [comment]
Did it solve the problem?

**Comment by kentcdodds** [comment]
You have one process to run cross-env and cross-env spawns another process with the right environment variables set. There's no other way to do this I'm afraid.
