### ISSUE TITLE
Is Tilde Expansion (as in Bash) supported by the tool?

### ISSUE THREAD

**Issue by anishmittal2020** [kentcdodds/cross-env#204]
I want to set Env. variable as `Format=~/bin/Format`. Can I do it as follows:

```json
{
  "scripts": {
    "parentScript": "cross-env Format=\"~/Format\" npm run childScript",
  }
}
```

Actually, I am not sure if the tilde expansion still works. How can I confirm that the tilde expansion works?

I tried to test as follows (with [okonet/lint-staged: 🚫💩 — Run linters on git staged files](https://github.com/okonet/lint-staged)):

```bash
{
  "linters": {
    "*.md": [
      "cross-env qPre=~/\"opt/bin/qPreProcess\" echo ${qPre} > ~/Test1",
      "cross-env qPre=\"${HOME}/opt/bin/qPreProcess\" echo ${qPre} > ${HOME}/Test2",
      "cross-env qPre=\"/home/nikhil/opt/bin/qPreProcess\" echo ${qPre} > /home/nikhil/Test3"
  ]
}
```

But, none of the Test1, Test2 or Test3 gets generated.

**Comment by anishmittal2020** [comment]
Yes it supports!

**Comment by anishmittal2020** [comment]
Actually, I am not sure if the tilde expansion still works. How can I confirm that the tilde expansion works?

**Comment by kentcdodds** [comment]
Hi @anishmittal2020,

It's not a supported feature. And there's no plan to support it. Sorry.

**Comment by anishmittal2020** [comment]
@kentcdodds Is `${HOME}` supported?
