### ISSUE TITLE
URLs on Windows 10 are messed up

### ISSUE THREAD

**Issue by plaskevich** [kentcdodds/cross-env#205]
- `cross-env` version: 5.2.0
- `node` version: 10.19.0
- `npm` (or `yarn`) version: 6.9.0

Relevant code or config
package.json :
```javascript
"print": "cross-env-shell \"echo https://google.com\"",
```

What you did:
```
npm run print
```

What happened: The result was 
```
https:\google.com
```

It seems there is some problem with slash conversion and it messes up the URLs.

**Comment by kentcdodds** [comment]
Hi @plaskevich,

Try this:

```
"print": "cross-env-shell \"echo https:\/\/google.com\""
```

Good luck!
