### ISSUE TITLE
cross-env with git tag

### ISSUE THREAD

**Issue by BhaveshSGupta** [kentcdodds/cross-env#206]
- `cross-env` version: ^5.2.0
- `node` version: 10.15.0
- `npm` (or `yarn`) version: 6.4.1

Relevant code or config

```javascript
"make": "cross-env APP_ENV=production cross-env APP_VERSION=`git tag --points-at HEAD` cross-env APP_COMMIT=`git rev-parse HEAD` webpack --config webpack.config.js"
```

What you did:
When using above code in package.json and running it as npm run-script make

What happened:

Gives below error.
![image](https://user-images.githubusercontent.com/4209637/62933661-55201280-bde0-11e9-92e2-8e15b06da0d5.png)

Reproduction repository:

Problem description:

Suggested solution:

**Comment by jaller94** [comment]
The common patterns seems to be `crossenv [declaration] [command]` where your command would be another `crossenv`.
Have you tried an explicit end at the end of each command?
```
cross-env APP_ENV=production; cross-env APP_VERSION=`git tag --points-at HEAD`; cross-env APP_COMMIT=`git rev-parse HEAD` webpack --config webpack.config.js
```
Not sure if that will carry on the variables though.
I thought this may be the solution:
```
"make": "cross-env-shell \"APP_ENV=production cross-env APP_VERSION=`git tag --points-at HEAD` cross-env APP_COMMIT=`git rev-parse HEAD` webpack --config webpack.config.js\"",
```

**Comment by jaller94** [comment]
What is the minimal command to reproduce this?

Does this work?  
```
"make": "cross-env APP_VERSION=`git tag --points-at HEAD` echo $APP_VERSION`
```

**Comment by BhaveshSGupta** [comment]
@jaller94, I was able to fix this by you using something like
  ` "make": "cross-env APP_ENV=production cross-env APP_VERSION=\"git tag --points-at HEAD\" cross-env APP_COMMIT=\"git rev-parse HEAD\" webpack --config webpack.config.js"`
