### ISSUE TITLE
cross-env not setting custom process environment variables on windows OS

### ISSUE THREAD

**Issue by maheshkrsna** [kentcdodds/cross-env#208]
- `cross-env` version: ^5.2.1
- `node` version: 10.15.1
- `npm` version: 6.4.1

Relevant code or config

`package.json > "scripts"`
```javascript
"start": "cross-env DEBUG=true && webpack-dev-server";
```
`webpack.config.js`
```javascript
mode: process.env.DEBUG ? 'development' : 'production',
```

What you did:
add the above code snippets in a react project and run it as an npm script on windows OS.

What happened:
React code runs with production version instead of debug version. Looks like ` cross-env` isn't setting the debug variable.
There are no errors thrown though.

Reproduction repository: 

Problem description: `cross-env` isn't setting custom process environment variables on windows OS.

Suggested solution:

**Comment by bibo5088** [comment]
Just tested on windows 
```JS
//index.js
console.log(process.env.NODE_ENV);
```

```JSON
"scripts": {
  "dev": "cross-env NODE_ENV=dev node index.js",
  "prod": "cross-env NODE_ENV=prod node index.js",
  "error": "cross-env NODE_ENV=dev && node index.js"
}
```

dev prints "dev"
prod prints "prod"
error prints undefined

**Comment by maheshkrsna** [comment]
@bibo5088  Yes, removing the `&&` worked. Thanks.

**Comment by rbhgaston** [comment]
May I ask why I have to remove the && ? @bibo5088

**Comment by bibo5088** [comment]
`&&` is used in shells to run multiple commands in sequence.  
 So `cross-env DEBUG=true && webpack-dev-server` would be read as run command `cross-env DEBUG=true` and after that run command `webpack-dev-server`.  
`cross-env` would not receive `webpack-dev-server` as an argument and wouldn't run it.
