### ISSUE TITLE
Suggestion: support reading environment variables from a file.

### ISSUE THREAD

**Issue by knpwrs** [kentcdodds/cross-env#21]
A few ideas for this:

```
cross-env TEST
cross-env ./env.json
```

In the first example `cross-env` would see a single argument with no equals sign and look for a `"VAR": "VAL"` mapping somewhere (e.g., in `package.json` under `config.environments`, similar to how `ghooks` looks for hook definitions under `config.ghooks`).

In the second example `cross-env` would see a relative path to a file and `require` that. This file would just be a simple `"VAR": "VAL"` listing in a single object. YAML is tempting here, but probably very unnecessary.

Both of these options would allow for more easily reusable environments and promote shorter script strings when lots of environment variables are used (or even just long environment variables).

If pattern matching against the argument is too shaky, we can always implement a flag or two:

```
cross-env -e TEST
cross-env -f ./env.json
```

**Comment by kentcdodds** [comment]
Thanks for thinking this through @knpwrs, but I'm not really interested in expanding this library to do anymore than it does currently. If you'd like to do more with it then you can feel free to fork it, but I'd like to keep this small and specific.

**Comment by toddbluhm** [comment]
@knpwrs I just created that very lib because I needed the same thing for a [sequelize](https://github.com/sequelize/sequelize) PR. You can find my util here [`env-cmd`](https://www.npmjs.com/package/env-cmd)

@kentcdodds Thank you so much for creating `cross-env` and inspiring me to create my own with new functionality I needed 😄

**Comment by kentcdodds** [comment]
Wonderful! Thank you!

**Comment by kentcdodds** [comment]
Would you like to add something to the README? Like a *Related Projects* section?

**Comment by toddbluhm** [comment]
Yeah that would be great! I can make a PR for that and I will add a similar section to env-cmd's README as well.

**Comment by knpwrs** [comment]
@toddbluhm You beat me to it! I was going to create `use-env` as soon as I needed it.

**Comment by toddbluhm** [comment]
@knpwrs I actually really like that name. Wish I had thought of it before.

**Comment by knpwrs** [comment]
You took a slightly different approach than I was going to take. I was going to make `cross-env` a peer dep and go after the `crossEnv` function exported from `cross-env/dist/index.js` (since `main` in `package.json` is set to `src/index.js`). Though I suppose that may not technically be a public api so that may or may not have been a good idea.

**Comment by toddbluhm** [comment]
I seriously considered going that route at first too, but then I just wanted the fun of writing it all from scratch, along with minimal dependencies. Weirdly enough, I actually enjoy writing parsing code.
