### ISSUE TITLE
Accessing variable with $ does not work on windows with cross-env-shell

### ISSUE THREAD

**Issue by raDiesle** [kentcdodds/cross-env#210]
- `cross-env` version: 5.2.1
- `node` version: 10.16.0
- `npm` version: 6.9.0

On Windows 10, the example from documentation does not print variable by using $GREET, but %GREET% works:

```javascript

{
"name": "test",
"version": "1.0.0",
"description": "",
"main": "index.js",
"scripts": {
"test": "echo "Error: no test specified" && exit 1",
"parentScript": "cross-env GREET="Joe" npm run childScript",
"childScript": "cross-env-shell "echo Hello $GREET""
},
"author": "",
"license": "ISC",
"dependencies": {
"cross-env": "5.2.1"
}
}

```

By performing
```javascript
npm run parentScript
```

In .npmrc PowerShell is configured

**Comment by raDiesle** [comment]
I figured out by switching PowerShell back to default CMD, it works!

I guess documentation should be updated or to support PowerShell.

**Comment by kentcdodds** [comment]
Sorry for not responding to this earlier. It's been long enough that I'm going to close this issue. If you're still experiencing problems, please open a new issue.
