### ISSUE TITLE
Cross-env does not work under raspberry pi (arm32)

### ISSUE THREAD

**Issue by mmc41** [kentcdodds/cross-env#214]
- `cross-env` version: 6.0.3
- `node` version: 12.10.0
- `npm` (or `yarn`) version: npm 6.10.3

Relevant code or config
In package.json scripts:
"test": "cross-env LIBXTRACE=trace ts-node xxx.ts"

Problem description:
Error "cannot find module 'which' in internal/modules/cjs/loader.js:775

**Comment by kentcdodds** [comment]
Hi @mmc41,

This library depends on `cross-spawn` which depends on `which`. If you're seeing that error my guess is that your dependencies were not installed properly.

Sorry, there's not much that's actionable about this issue, so I'm going to close it.

**Comment by mmc41** [comment]
just tested using yarn instead of npm and here it works. So it must be a npm problem.
