### ISSUE TITLE
Passing url parameter on windows breaks

### ISSUE THREAD

**Issue by amsterdamharu** [kentcdodds/cross-env#221]
- `cross-env` version: 5.2.0
- `node` 8.16.2:
- `npm`  version: 6.4.1

Following script in package.json :

```    
"op": "cross-env \"echo \"https://hello.world\"\"",
```
On mac it outputs: `https://hello.world` and on windows it outputs  `https:\hello.world`

I am unable to pass urls as parameters in package.json script because cross-env and cross-env-shell will destroy them on windows.

**Comment by kentcdodds** [comment]
https://github.com/kentcdodds/cross-env/issues/257
