### ISSUE TITLE
v7.0.1 leaves processes hanging on Windows

### ISSUE THREAD

**Issue by XhmikosR** [kentcdodds/cross-env#230]
- `cross-env` version: 7.0.1
- `node` version: 12.16.1
- `npm` version: 6.13.4

What you did:

```
npm run make-fake-data && cross-env REACT_APP_FAKE_API=1 npm run start
```

What happened:

![75963152-aeab7400-5ecd-11ea-9e76-3c6a1b2d6c6f](https://user-images.githubusercontent.com/349621/75963840-e2d36480-5ece-11ea-840e-68c259bb8e7d.gif)

Reproduction instructions:

Assuming you are on Windows:

```
git clone https://github.com/pi-hole/web -b development
npm i && npm run start-fake
```

Then try to `ctrl+c` the process. One needs to hit `ctrl+C` twice. If you don't do it twice, then you can check the task manager and you will see `node.exe` left running

---

Initially reported in the PR that introduced the issue [here](https://github.com/kentcdodds/cross-env/pull/227#issuecomment-595096003). Going back to v7.0.0 works as expected.

**Comment by kentcdodds** [comment]
This has been fixed in 7.0.2
