### ISSUE TITLE
OS X APPDATA

### ISSUE THREAD

**Issue by jiangyuan** [kentcdodds/cross-env#24]
macOS `env.APPDATA` should be `undefined`, but `cross-env` created a `'undefined'` string.

this could be better:
```js
if (process.env.APPDATA) {
  envVars.APPDATA = process.env.APPDATA;
}
```

**Comment by kentcdodds** [comment]
Would you like to http://makeapullrequest.com ?

**Comment by jiangyuan** [comment]
I'll try it.
