### ISSUE TITLE
More than 3 parent directories (..) in path ignored on Windows

### ISSUE THREAD

**Issue by abidingotter** [kentcdodds/cross-env#244]
- `cross-env` version: 7.0.2
- `node` version: 12.18.0
- `npm` (or `yarn`) version: 6.14.5

Multiple parent directories (in my case, 5) has been treated as 3

package.json
```javascript
{
...
  "scripts": {
    "prepare": "cross-env-shell \"cd ../../../../../otherproject && npm ci build\""
```

Output
```
> cross-env-shell "cd ../../../../../otherproject && npm ci build"

'..\..\..\otherproject ' is not recognized as an internal or external command,
operable program or batch file.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn ..\..\..\otherproject && npm ci build ENOENT
    at notFoundError (….\node_modules\cross-spawn\lib\enoent.js:6:26)
```
Note that only three sets of ".." are present in the error.  Placing an absolute path in the command works, so the problem is restricted to the parsing of the parent directories.

**Comment by abidingotter** [comment]
Note that this is not an issue for the developers using a Linux based OS

**Comment by kentcdodds** [comment]
https://github.com/kentcdodds/cross-env/issues/257
