### ISSUE TITLE
It seems that cross-env NODE_ENV=something doesn't work

### ISSUE THREAD

**Issue by eliagentili** [kentcdodds/cross-env#25]
Hi,
i use cross-env on my mac.
I've tried it with node v6.3.1 and v5.12.0, but it seems that it doesn't work well.
After launching

```
$ ./node_modules/.bin/cross-env NODE_ENV=development
```

and

```
$ printenv
```

i can't see `NODE_ENV`.

But, if i try to set it with

```
$ export NODE_ENV=development
```

works fine.

Maybe there are some breaking changes?

**Comment by kentcdodds** [comment]
`cross-env` only adds the environment variable during the process that it spawns when it runs your command. So you'd have to do:

```
$ ./node_modules/.bin/cross-env NODE_ENV=development printenv
```

It's unlikely that `corss-env` will change in this regard.

**Comment by rroman81** [comment]
That’s not working even in the same process:

```
cross-env NODE_ENV=production node ./dist/main.js
```

However, this works:
```
export NODE_ENV=production node ./dist/main.js
```
