### ISSUE TITLE
Variables empty

### ISSUE THREAD

**Issue by johannesjo** [kentcdodds/cross-env#250]
- `cross-env` version: 7.0.2
- `node` version: 12.10
- `npm` (or `yarn`) version:  yarn 1.22.4

Relevant code or config
```
{
  "scripts": {
    "d": "cross-env FIRST_ENV=one SECOND_ENV=\"two\" echo \"III $FIRST_ENV $SECOND_ENV III\"",
  }
}
```
I tried different combinations of the above script, but all of them print out:
```
$yarn d
yarn run v1.22.4
$ cross-env FIRST_ENV="one" SECOND_ENV="two" echo "III $FIRST_ENV $SECOND_ENV III"
III   III
Done in 0.08s.
```

Am I missing something obvious?

**Comment by dwiyatci** [comment]
Some believes something got changed since MacOS 10.15.x (#222).

You might also be interested in #148 and #172. :)

**Comment by kentcdodds** [comment]
https://github.com/kentcdodds/cross-env/issues/257
