### ISSUE TITLE
'lodash.assign' vs 'Object.assign'

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [kentcdodds/cross-env#28]
[For how it it used](https://github.com/kentcdodds/cross-env/blob/master/src/index.js#L19), wouldn't `Object.assign` work over `lodash.assign`?  I tried swapping them out and the tests all passed.  `dist` was .22kb lighter, too.
If I'm not missing something here, I can submit a Pull Request.

**Comment by kentcdodds** [comment]
If we do that, we'd have to drop support for Node < 4 which is fine, we'd just need to push a breaking change. Feel free to file a PR.

**Comment by wtgtybhertgeghgtwtg** [comment]
Oh, right, `main` points to `src`.
Filed in #29.  Hope I formatted the commit right.

**Comment by DavidWells** [comment]
Looks like this is breaking in electron. Ref: https://gist.github.com/DavidWells/2c79ce5864f2b3c224423c7db53b3b17

https://github.com/chentsulin/electron-react-boilerplate/ throws when trying to run the `npm run dev` command.

Should we revert this back to lodash for now? =)

**Comment by kentcdodds** [comment]
Sorry, `Object.assign` is supported in all environments version of node that `cross-env` targets (>=4). My guess is there's something odd about your environment. You can use an older version of `cross-env` if you need to.

**Comment by DavidWells** [comment]
Thanks Kent! 

Take the day off for your birthday. You deserve it.

I'll figure this out :)
