### ISSUE TITLE
Proxy all events

### ISSUE THREAD

**Issue by EnzoMartin** [kentcdodds/cross-env#31]
Currently only `SIGINT` is proxied to the resulting process, which runs into some limitations when using it with Docker (uses `SIGTERM` as well) and when sending other process signals, as they're not passed through to the process that gets spawned, resulting in sadness.

**Comment by kentcdodds** [comment]
Thanks for reporting this. Would you be willing to [makeapullrequest.com](http://makeapullrequest.com) to fix it?

**Comment by EnzoMartin** [comment]
Hm, maybe, I'm not quite sure how best to handle it. Quick untested idea:

```javascript
const signals = ['SIGTERM', 'SIGINT', 'SIGPIPE', 'SIGBREAK', 'SIGWINCH'];

function crossEnv(args) {
  // tuff
  signals.forEach((signal) => {
    process.on(signal, (...eventArgs) => proc.emit.apply(proc, eventArgs));
  });
}
```

Though that won't proxy other events and needs to be updated if Node adds more signals

**Comment by kentcdodds** [comment]
I'm fine with that approach. Is there any internal module we can use that has that list of signals so we don't have to update in the future?

**Comment by kentcdodds** [comment]
If not, I'm good hardcoding it and keeping it updated.

**Comment by EnzoMartin** [comment]
There isn't a built-in event list that I can see no

**Comment by EnzoMartin** [comment]
Another option would be to use something like https://github.com/asyncly/EventEmitter2 and wrap `process`, or,  injecting `process.emit` with a function call to patch the event through

**Comment by kentcdodds** [comment]
you're suggesting using `onAny` from `EventEmitter2`? Seems interesting. Though I think I actually like monkey-patching `process.emit` a little better.

**Comment by EnzoMartin** [comment]
Yes, though I think using `EventEmitter2` is a bit overkill for this IMO

**Comment by kentcdodds** [comment]
Agreed. Let's monkey-patch `process.emit` :+1:

**Comment by EnzoMartin** [comment]
🐒

**Comment by EnzoMartin** [comment]
I'll get a PR up later this week, need to fix the tests

**Comment by EnzoMartin** [comment]
So while testing various things on how best to do this (also wanted to see about proxy'ing all events) I've noticed that the current version of the module actually leaves zombie processes behind, as the `child` processes aren't killed when the parent process is killed (at least on Windows).

**Comment by kentcdodds** [comment]
> I've noticed that the current version of the module actually leaves zombie processes behind

So this is resolved as part of your merged PR too right?

**Comment by EnzoMartin** [comment]
Yep
