### ISSUE TITLE
Handle forward/backward slash for executing binaries

### ISSUE THREAD

**Issue by fatso83** [kentcdodds/cross-env#33]
I made [convert-slash-exec](https://github.com/fatso83/convert-slash-exec) to be able to execute binaries regardless of which platform I was on (see link for details).

Would integrating this into cross-env be reasonable? Wrapping commands after command to handle all the various nuances/annoyances when working cross platform can build a quite long string ... Not to mention stuff like #23. Having one tool to handle these things would be great.

This might be out of scope, in which case a tool to wrap all of this functionality might be in place.

**Comment by kentcdodds** [comment]
Interesting. I wonder why I haven't had any complaints from people about this kind of thing before. I think that until I get some complaints, we'll leave things as they are. If it's a problem for people, they can compose our tools together. Thanks!
