### ISSUE TITLE
3.1.0 package has a bad build

### ISSUE THREAD

**Issue by ericf** [kentcdodds/cross-env#34]
Greekeeper failed by build because when running `cross-env` it couldn't find `./command.js`: https://travis-ci.org/yahoo/react-intl/jobs/165011187#L192

Looking at the package on npm, it appears there's no `command.js` in `./dist/`: https://unpkg.com/cross-env@3.1.0/dist/

**Comment by kentcdodds** [comment]
Whoops, that's my bad for not reviewing properly. I'll fix that. Thanks for the report!

**Comment by EnzoMartin** [comment]
New PR should fix it

**Comment by kentcdodds** [comment]
Fixed, released `3.1.1`, deprecated 3.1.0. Thanks!
