### ISSUE TITLE
Read env variables from JSON file

### ISSUE THREAD

**Issue by con-ssc** [kentcdodds/cross-env#44]
Is there a way to make cross-env read env variables from a JSON file?
```JSON
{
    "NODE_ENV": "DEBUG",
    "BING_KEY": "dd888c15-19c4-4eda-ab98-f24cea171abe",
    ...
}
```

**Comment by kentcdodds** [comment]
Hey @con-ssc,
That's something that I've decided is out of scope for cross-env, but you might look at https://github.com/toddbluhm/env-cmd (which is linked in the README). Thanks!
