### ISSUE TITLE
Commits Incorrectly Fail Due To linebreak-style Issues On Windows When Git Config core.autocrlf = true

### ISSUE THREAD

**Issue by compumike08** [kentcdodds/cross-env#47]
I forked your repository to commit a small change, which I intended to contribute back to your repo via pull request. However, after I made the change using my Windows computer and attempted to commit by running `npm run commit` and answering the commitizen prompts, the commit failed to complete due to lint errors in a number of files which I never even touched. Specifically, the `linebreak-style` lint rule was complaining that a number of files had `CRLF` linebreak characters instead of `LF` characters. I completely understand why this check is in place, as Windows editors often silently convert `LF` to `CRLF`, and if left unchecked this can cause problems for other systems (not to mention strange behavior from Git itself) if those changed linebreak characters get committed back into the repository and pushed to the remote.

However, in my case I have the global git config flag `core.autocrlf` ([see documentation](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace)) set to `true` on my Windows machine (it applies to all repositories on my machine). This resolves the linebreak character issue by causing Git to automatically covert `LF` characters to `CRLF` in my working directory when checking out files from the repository, and then automatically converting `CRLF` back to `LF` when file changes are staged to the index (and subsequently committed to the repository). This ensures that the repository always has `LF` characters, while also enabling Windows users who set `core.autocrlf` to `true` to have `CRLF` used instead in the files in their working directories.

Unfortunately, the way you currently have your lint rules configured, every time someone tries to commit it checks the linebreak characters in **every** file in the working directory, even if that file is not staged to be committed. This is causing all of my commit attempts to fail, as even though the files which I changed and staged to be committed have the correct `LF` linebreak characters (as `core.autocrlf=true` converted 'CRLF' back to 'LF' in those files when I staged them), your lint check is still detecting the `CRLF` characters in all of the other files in my working directory, even though I never made changes to them and did not stage them (those files have `CRLF` characters because `core.autocrlf=true` converted `LF` to `CRLF` when the files were checked out into my working directory).

I would suggest changing your lint checks for `linebreak-style` to only be run on whatever is currently staged in the index, instead of on every file in the working directory, if that is possible. Otherwise, anyone on a Windows machine who has their global Git config for `core.autocrlf` set to `true` will never be able to commit (setting `core.autocrlf` to true on Windows machines is best practice, as it prevents Git from ever committing `CRLF` characters into the repo accidentally).

![screenshot1](https://cloud.githubusercontent.com/assets/8941730/21597068/49590906-d112-11e6-8bcc-cd2b7f1e7754.png)

**Comment by kentcdodds** [comment]
Hi there! Thank you so much for digging into this issue so thoroughly! I've added `.gitattributes` to the project. If you could please re-clone everything it should work ok for you now. Sorry about that. Most of my repos have this now.
