### ISSUE TITLE
stdio doesn't appear to be getting written to

### ISSUE THREAD

**Issue by 321ckatz123** [kentcdodds/cross-env#51]
Following the examples from nyc (https://github.com/istanbuljs/nyc#user-content-use-with-babel-plugin-istanbul-for-es6es7es2015-support), I set up my package.json file to look like this:

`test: cross-env NODE_ENV=test nyc mocha --compilers js:babel-register --recursive \"test/**/*.js\"`

This command would fail and not give any Error so I couldn't really tell what was happening.

When I removed the cross-env command, as in:

`test: nyc mocha --compilers js:babel-register --recursive \"test/**/*.js\"`

I saw that some previous refactoring had changed a path to a file and an import was breaking.

`Error: Cannot find module '../../../../../shared/components/genericTable/GenericTableCellText'`

I'm sure I'm just doing something dumb, but it appears that cross-env is eating that error when it gets called (being cross-env spawns the process). I cannot find anything in the README or looking through the code to prevent this, so not sure what I am doing wrong...

**Comment by kentcdodds** [comment]
That's annoying! Sorry about that. Do you think you could do a little more digging and perhaps come up with a repo that reproduces the error? That would be very helpful! Thanks!

**Comment by 321ckatz123** [comment]
I should be able to whip up a test repo quickly tomorrow, but won't have time to investigate for a little bit beyond proving it's reproducible given a bare repo.

**Comment by 321ckatz123** [comment]
I created a bare-bones repo, but was not able to reproduce the behavior, which obviously leads me to believe that I am doing something dumb. Digging in a little further I think I know what's happening (and it was user error, as assumed).

Developing on Windows, running the command

`npm run test > out.txt`

does correctly show the module is missing error, whereas just running 

`npm run test` 

does not, but it DOES show other things related to nyc (like code coverage, even if the coverage is all basically non-existent because the tests didn't run).

As such, I believe what is happening is that cross-env was correctly always showing it, but I couldn't scroll up far enough to see (as Windows command prompts stop after a couple hundred lines).

Sorry for bugging you.

**Comment by kentcdodds** [comment]
You're good. Thanks for looking into it. Good luck on things!
