### ISSUE TITLE
run npm sub-commands

### ISSUE THREAD

**Issue by danielo515** [kentcdodds/cross-env#52]
Hello,

I think it is worth mentioning that you can use cross-env to run npm scripts with different variables set.

I know that you can not do

```js
    "parentScript": "cross-env GREET='Joe' ",
    "childScript": "npm run parentScript && echo Hello $GEET"
```

But if you want to split a command into several ones, or separate the environment variables from the actual command execution, you can do it this way:

```bash
    "parentScript": "cross-env GREET='Joe' npm run childScript",
    "childScript": "echo Hello $GEET"
```

So instead of run the childScript you run the parent. This is quite useful for launching the same command with different env variables or when the environment variables are too long to have everything in one line.

Regards

**Comment by kentcdodds** [comment]
That's super! Could you add that note to the README?

**Comment by danielo515** [comment]
Sure!
