### ISSUE TITLE
Extend to allow running local node in windows/linux

### ISSUE THREAD

**Issue by OracPrime** [kentcdodds/cross-env#54]
A number of projects want to avoid version problems by using their local copy of node.  So an entry might be
  "scripts": {
    "clean": "../../node_modules/.bin/rimraf build"
}

Unfortunately this fails on windows because although 

  "scripts": {
    "clean": "rimraf build"
}

picks up rimraf.cmd, if you specify the path explicitly, it doesn't.  So it occured to me that if cross-env could do this, it might make everything better:

  "scripts": {
    "clean": "cross-env PATH=$(npm bin);$PATH rimraf build"
}

**Comment by kentcdodds** [comment]
Very interesting! I'm 60% interested in adding this. Would you like to try and convince me with a pull request? (http://makeapullrequest.com)

**Comment by OracPrime** [comment]
OK, having dug a bit deeper, I think the path is irrelevant.  The problem is the use of spawn in index.js.  Spawn (AFAICT) works fine if you're talking about an executable, but not a cmd file.  So perhaps we need something like this:

let envCommand=command+ (/^win/.test(process.platform) ? '.cmd' : '');
const result = spawnSync(envCommand, args, opts);

However this clearly only needs to be done if the original is going to fail.  How exception averse are you?  My "catch-all" approach to this, rather than examining commnd and seeing if it lacks an extent, is to try it unaltered, catch the ENOENT, and retry with .cmd.

And since you're using cross-spawn, I wonder if that is the right place for the fix instead??

As an aside, do you have any tips on how to test & debug something which is part of the node_module infrastructure?

**Comment by OracPrime** [comment]
Sorry for the false alarm guys, cross-env is working just fine.

Changing
"scripts": {
"clean": "../../node_modules/.bin/rimraf build"
}
to
"scripts": {
"clean": "cross-env ../../node_modules/.bin/rimraf build"
}

works just fine.
