### ISSUE TITLE
How is cross-env different from dotenv ?

### ISSUE THREAD

**Issue by arshdkhn1** [kentcdodds/cross-env#56]

**Comment by kentcdodds** [comment]
`cross-env` is a CLI that will spawn a process for the command you give it with the environment variables set as you specify in the command.

`dotenv` will spawn the process with the environment variables based on a `.env` file.

Both are useful. Depends on your needs.

**Comment by arshdkhn1** [comment]
I am sorry, if it's not the right place to ask that question.

**Comment by kentcdodds** [comment]
Nope, you're fine. This was an ok place to ask the question.

**Comment by xahon** [comment]
why doesn't cross-env allow `source` `.env` file and use it instead of `dotenv` module?

**Comment by KresimirCosic** [comment]
So you're saying that `cross-env` is literally the same thing from native Webpack's environment variables -  as it is in their documentation?

`webpack --env.PORT=3000 --env.ENV=development --config webpack.common.js` for example, the difference is being in `module.exports` you don't set it to an object, but to a function which receives an `environment` object, and you can extract data from there and do logic where necessary:

```javascript
module.exports = env => {
  // Use env.<YOUR VARIABLE> here:
```

**Comment by kentcdodds** [comment]
This project was created years ago. Long before the `--env` flag existed for webpack. So maybe the examples in the README are dated. But there are still plenty of situations where you'd want to run a script with environment variables set.
