### ISSUE TITLE
how could you compile the cource code?

### ISSUE THREAD

**Issue by zzzgit** [kentcdodds/cross-env#61]
Hello,I found that the source code is written in ES6,but there is no tool and configuration exist to compile it.
So,I would like to ask how could you compile it automatically.

**Comment by kentcdodds** [comment]
The source is transpired using babel. You can see the script used in the package.json. The build is run before publishing and the built version of the code is what is released. You can learn more about how all this works here: http://kcd.im/write-oss

**Comment by zzzgit** [comment]
Thank you very much
