### ISSUE TITLE
can it supports multi variables?

### ISSUE THREAD

**Issue by zzzgit** [kentcdodds/cross-env#62]
`cross-env foo=bar fo=ba webpack`

According to the source code,I think this will get an error,right?

**Comment by kentcdodds** [comment]
Yes it does support multiple variables in a single command

**Comment by zzzgit** [comment]
Why not show it in the documentation?
And I will have a try for that functionality.

**Comment by kentcdodds** [comment]
Feel free to [makeapullrequest.com](http://makeapullrequest.com) to add it to the docs :)

**Comment by Darmikon** [comment]
Hi. What's the proper way to set multiple variables? ```cross-env foo=bar fo=ba webpack``` or ```cross-env foo=bar cross-env fo=ba webpack``` . Thanks in advance

**Comment by kentcdodds** [comment]
The first is correct
