### ISSUE TITLE
Failes on installation

### ISSUE THREAD

**Issue by Alexsey** [kentcdodds/cross-env#68]
Type this
```
> npm install cross-env
```
And get this
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @vlsdatagroup/member-back@0.4.1 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cross-env"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! path C:\Users\_\Projects\member-back\node_modules\cross-env\bin\cross-env.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\_\Projects\member-back\node_modules\cross-env\bin\cross-env.js'
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\_\Projects\member-back\node_modules\cross-env\bin\cross-env.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\_\Projects\member-back\npm-debug.log
```

**Comment by Pegasuz** [comment]
My builds are also failing:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! path /builds/buildserver/projectname/node_modules/cross-env/bin/cross-env.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/builds/buildserver/projectname/node_modules/cross-env/bin/cross-env.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/builds/buildserver/projectname/node_modules/cross-env/bin/cross-env.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /builds/buildserver/projectname/npm-debug.log

ERROR: Build failed: exit code 254

**Comment by hckhanh** [comment]
I receive a similar bug like two guys bellow:
https://travis-ci.org/hckhanh/games-searcher/builds/207650774

**Comment by ponsfrilus** [comment]
+1

**Comment by kentcdodds** [comment]
this should be fixed in a minute or two. Sorry about that!

**Comment by looterz** [comment]
Thanks for the quick fix @kentcdodds .
