### ISSUE TITLE
3.2.0 appears broken

### ISSUE THREAD

**Issue by kellyselden** [kentcdodds/cross-env#69]
`npm ERR! enoent ENOENT: no such file or directory, chmod '/home/travis/build/kellyselden/package-hint-historic-resolver/node_modules/cross-env/bin/cross-env.js'`

https://travis-ci.org/kellyselden/package-hint-historic-resolver/jobs/207694281

**Comment by djMax** [comment]
Yep, this has broken all our builds. Sure hope it's fixed soon and 3.2.0 deprecated or unpublished.

**Comment by kentcdodds** [comment]
Yeah, my blunder. Should be fixed in a minute

**Comment by kellyselden** [comment]
Thanks for the quick work @kentcdodds !
