### ISSUE TITLE
Handle platform-specific list delimiters

### ISSUE THREAD

**Issue by DanReyLop** [kentcdodds/cross-env#80]
For more context: https://github.com/elijahmanor/cross-var/issues/3

Variables like `$PATH` or `$NODE_PATH` contain lists of items that are separated by `;` in Windows and `:` in Unix. If would be good if `cross-env` handled this transparently.

**Previous proposed solution**: `$:` is converted to `:` on Unix, `;` on Windows.
Example:

- Input: `PATH=$PATH$:lib npm start`
- Output (Win): `PATH=%PATH%;lib npm start`
- Output (Unix): `PATH=$PATH:lib npm start`

The drawback is that syntax is a bit confusing, it looks like the variable is `$PATH$`.

**Alternate solution:** `:` in the value of a variable is converted to `;` on Windows, `;` is converted to `:` on Unix. To put the literal `:` or `;` values, escape with a backslash (`\:`, `\;`).
Example:
- Input: `PATH=$PATH:lib GREET=Hello\:you npm start`
- Output (Win): `PATH=%PATH%;lib GREET=Hello:you npm start`
- Output (Unix): `PATH=$PATH:lib GREET=Hello:you npm start`

Note that this would technically be a breaking change, and such a `semver` *major* release.

**Comment by DanReyLop** [comment]
cc/ @kentcdodds @elijahmanor

**Comment by kentcdodds** [comment]
Thanks for bringing this up @DanReyLop!

What if we made the escaping required on the variable side of things? So you'd have to do:

```
PATH=$PATH\:lib GREET=Hello:you npm start
```

Would that work?

**Comment by DanReyLop** [comment]
Well it would work, and it would be more backwards-compatible, but I feel like the other way is more natural.

Just like in a RegExp, you use the "reserved" characters for their intended meaning, and if you want to use them literally, you have to escape them (not the other way around). In implementing this feature, we are basically acknowledging that `:` (and `;` in Windows) are special characters on ENV variables values.

Anyway, this feels like a lot of bikeshedding for a single-char feature, just pick one syntax and I'll make a PR :)

**Comment by kentcdodds** [comment]
Ok, I'm convinced. Let's go with your suggestion :+1: Thanks!

**Comment by DanReyLop** [comment]
Fixed in #93
