### ISSUE TITLE
Breaking change if using in a js script

### ISSUE THREAD

**Issue by thomasthiebaud** [kentcdodds/cross-env#84]
I was using `cross-env` with version `3.1.4` like this

    const crossEnv = require('cross-env');
    ...
    crossEnv(['node', 'bin/execute', ...argv._]);

I recently migrated to the latest version `3.2.3` and I had this error

> TypeError: crossEnv is not a function

I finally found the error, I needed to change the import to 

    const crossEnv = require('cross-env').default;

It broke my build, so maybe more peoples are facing the same issue. Would it be possible to add some more documentation about it?

**Comment by kentcdodds** [comment]
Ah, yeah, it was never intended to be used like that. However, I'd be willing to accept a change to make it more ergonomic. You'd have to change [this](https://github.com/kentcdodds/cross-env/blob/920451ddb606a66cf9ebf193a498356ec0fa64d9/src/index.js#L4) to `module.exports = crossEnv`. Should be pretty straightforward. If you'd like to do this, please also verify that you can still use the binary in the normal way.

Thanks!

**Comment by kentcdodds** [comment]
Note also that I do not consider it a breaking change as it was never intended to be used that way and it's not documented. So you don't need to worry about this requiring a major release or anything.

**Comment by kentcdodds** [comment]
We're going to go ahead and put this in the next major version. If you want to do this, please open a PR to the `next` branch 👍

**Comment by thomasthiebaud** [comment]
Yes sure I can do it

**Comment by thomasthiebaud** [comment]
If I only replace

`export default crossEnv`

by

`module.exports = crossEnv`

I have an linter error (no default export). I can either :

- disable the rule (globally or on this line only)
- use both exports (it works, I didn't known before testing. I added a test for this case)

**Comment by kentcdodds** [comment]
Ah yes, just disable it with `// eslint-disable-next-line`

**Comment by thomasthiebaud** [comment]
Ok so I will modify my PR

**Comment by kentcdodds** [comment]
This will be released as soon as we merge the `next` branch (hopefully soon)

**Comment by kentcdodds** [comment]
Could you please try out `cross-env@beta` and make sure this resolves your issue?

**Comment by thomasthiebaud** [comment]
It solves my problem (version `4.0.0-beta.0`)
