### ISSUE TITLE
Resolving vars in other vars

### ISSUE THREAD

**Issue by hgwood** [kentcdodds/cross-env#90]
On `master`, `cross-env MY_VAR=$MY_OTHER_VAR echo $MY_VAR` on Windows results in this command: `%MY_OTHER_VAR% echo %MY_VAR%`, which is incorrect. #86 fixes this.

On `next` (i.e. with #86 merged), it results in `echo %MY_VAR%`, which is correct. However, in the spawned process, `process.env.MY_VAR` is `%MY_OTHER_VAR%`, which is not very useful, and I would expect it to be *the value* of `MY_OTHER_VAR` from the environment in which cross-env is run.

An easy solution would be to replace variables by their value instead of their platform-specific form (cross-var does this), but I'm not sure that's what we want. In this scenario, `cross-env MY_VAR=$MY_OTHER_VAR echo $MY_VAR` becomes `echo <value of MY_OTHER_VAR>`.

Another solution is replace variables by their value *only* in the part of the command that sets new variables. In this scenario, `cross-env MY_VAR=$MY_OTHER_VAR echo $MY_VAR` becomes `echo %MY_VAR%` like today but `MY_VAR` is properly set to `<value of MY_OTHER_VAR>`. I think this is better, but it requires more work as `commandConvert` needs to be split into two or cover the two cases.

What do you think?

**Comment by kentcdodds** [comment]
Yes, let's Make this happen for the next major release :+1:

**Comment by hgwood** [comment]
I realized:
- cross-env seems to support converting Windows vars to Unix vars, even though this is not mentioned in the readme. Perhaps this feature could be dropped to reduce complexity. I think it is probably not used (still a breaking change).
- Now that cross-env uses the `shell` option of `spawn`, if cross-env is run on Unix, then the command string passed to cross-env can be passed to `spawn` verbatim. Then it becomes even more interesting to drop Windows->Unix conversion because we wouldn't even need to check anything if the platform is Unix.

What do you think?

**Comment by kentcdodds** [comment]
> converting Windows vars to Unix vars,

Yeah, I noticed that (sometimes you forget when so many people have contributed). Let's drop it. It was never intended to go both ways and it's confusing that it does.

> check anything if the platform is Unix.

Awesome, let's make that happen too! Thanks for all your help on this! :+1:

**Comment by kentcdodds** [comment]
Thanks to #94 by @DanReyLop, the issues you brought up are no longer a problem. Now implementing this "Resolving vars in other vars" thing should be more straightforward. This is the last thing we're waiting on for the release. Do you want to work on it?

**Comment by hgwood** [comment]
I planned to but looks like @DanReyLop needs this release out faster than me ;)
