### ISSUE TITLE
Support for variables in complex statements

### ISSUE THREAD

**Issue by elijahmanor** [kentcdodds/cross-env#92]
Due to a recent feature ([Convert environment vars](https://github.com/kentcdodds/cross-env/pull/32)) the `cross-var` package can almost be deprecated. The one thing the library could support that `cross-env` does not yet (to my understanding) is complex statements.

The API for complex statements is to wrap the contents in a string so that all the variables can be replaced and then executed. What do you all think of this API and would it fit well with `cross-env`? If this type of feature was added to `cross-env` then `cross-var` shouldn't be needed anymore.

```
{
  "version": "1.0.0",
  "config": {
    "port": "1337"
  },
  "scripts": {
    "simple1": "cross-var rimraf public/$npm_package_version",
    "simple2": "cross-var http-server public/$npm_package_version -p $npm_package_config_port",
    "complex": "cross-var \"node-sass src/index.scss | postcss -c .postcssrc.json | cssmin > public/$npm_package_version/index.min.css\""
  }
}
```

**Comment by kentcdodds** [comment]
This is actually going to be released soon! It was implemented in https://github.com/kentcdodds/cross-env/pull/89 and will be released when this is merged: https://github.com/kentcdodds/cross-env/pull/87

🎉

**Comment by elijahmanor** [comment]
@kentcdodds well that is great! that means i can re-record both the nps and cross-environment egghead lessons with just `cross-env`!

**Comment by kentcdodds** [comment]
And with nps-utils you can uninstall a bunch of the libs because they're supported by default!
