### ISSUE TITLE
Escape double dot

### ISSUE THREAD

**Issue by lmachens** [kentcdodds/cross-env#97]
Hey, I just tried out 4.0.0 and got an issue.

> BREAKING CHANGE: You now must escape : to use it in a value of you don't want it to be swapped with ; on Windows

So I tried to escape this line (package.json):

> "app": "cross-env MONGO_URL=mongodb://localhost:4000/database npm start"

to

> "app": "cross-env MONGO_URL=mongodb\\://localhost\\:4000/database npm start"

But this is not valid JSON (vscode told me about an "Invalid escape character in string").
It seems like there are only some characters allowed to escape in JSON. Take a look at [JSON](http://www.json.org/).

**Comment by lmachens** [comment]
Ok it works like this:
> "app": "cross-env MONGO_URL=mongodb\\\\://localhost\\\\:4000/database npm start"

**Comment by kentcdodds** [comment]
I'm glad it's working for you!
